import { useState, useEffect } from "react";

export type LanguageCode = "ro" | "en" | "es" | "fr" | "it";

export interface Language {
  code: LanguageCode;
  label: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "ro", label: "Română", flag: "🇷🇴" },
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
];

export const UI_TRANSLATIONS = {
  ro: {
    library: "Bibliotecă",
    authorAtelier: "Atelier Autor",
    store: "Librărie Store",
    importBook: "Importă Carte",
    howItWorks: "Cum funcționează",
    welcomeTitle: "Universul tău literar transpus în",
    welcomeTitleAccent: "pagini curate 3D",
    welcomeSubtitle: "Bine ați venit în cititorul interactiv dedicat pasionaților de carte. Importați romane în format ePUB sau fișiere TXT curat formatate, alegeți-vă tema vintage pergament perfect adaptată lecturii nocturne și bucurați-vă de mișcarea fizică realistă a paginilor care se îndoaie sub gestul de swipe.",
    importFirst: "IMPORTĂ PRIMUL EBOOK",
    supportNote: "Suportă tablete de orice mărime și telefoane mobile.",
    ownBooks: "Volume proprii",
    readingProgress: "Cărți în progres",
    totalChapters: "Capitole totale",
    activeBookmarks: "Marcaje active",
    continueReading: "Continuă lectura",
    deleteBookConfirm: "Sigur doriți să ștergeți această carte din colecția dumneavoastră?",
    deleteBookmarkConfirm: "Sigur doriți să ștergeți acest marcaj?",
    chapters: "Cuprins",
    bookmarks: "Marcaje",
    search: "Caută",
    searchPlaceholder: "Caută în această carte...",
    fontSize: "Mărime font",
    lineHeight: "Înălțime rând",
    layoutType: "Mod afișare",
    twoPageSpread: "Pagini duble",
    singlePage: "Pagini simple",
    noBooks: "Nu aveți nicio carte în bibliotecă.",
    dragDrop: "Trageți și plasați fișierele aici sau dați click pentru selectare",
    back: "Înapoi",
    soundEffects: "Efecte de sunet",
    closeReader: "Închide",
    translateBook: "Traducere Text",
    translateBookTitle: "Traducere Inteligentă AI",
    translateChapterBtn: "Tradu în",
    translatingText: "Se traduce textul prin AI...",
    translationSuccess: "Capitolul a fost tradus cu succes!",
    translationError: "Eroare la traducere. Reîncercați.",
    originalLanguage: "Text original (Limba cărții)",
    viewOriginalText: "Vezi textul original",
    translatedByAI: "Tradus automat cu Gemini AI",
    aboutBook: "Despre carte",
    authorName: "Nume autor",
    description: "Descriere",
    emptyBookmarks: "Niciun marcaj adăugat pe filele cărții.",
    addBookmarkTip: "Faceți clic pe steagul de marcaj din colțul paginii în timp ce citiți pentru a nota paragrafe importante.",
    bookmarksCount: "MARCAJE",
    chaptersCount: "CAPITOLE",
    searchResultsCount: "REZULTATE ÎN TOATĂ CARTEA",
    searchNoResults: "Niciun fragment găsit în text.",
    searchAtLeast2: "Scrie minimum 2 caractere pentru a lansa căutarea...",
    secuEmptySearch: "Localizează expresii sau cuvinte",
    searchSecuTip: "Scrie un cuvânt sau o propoziție în caseta de mai sus pentru a găsi toate fragmentele purtătoare și a le evidenția dinamic pe foile cărții.",
    searchTitleHint: "caută cuvinte cheie",
    themeParchment: "Pergament",
    themeWarmPaper: "Hârtie caldă",
    themeSlateDark: "Ardezie închis",
    themeMidnightVelvet: "Catifea de noapte",
    themeClassicWhite: "Alb clasic",
    aboutAuthor: "Despre Atelierul de Autor",
    authorIntro: "Scrieți și publicați propriile creații literare. Puteți deveni chiar dumneavoastră autorul operelor de pe raft!",
    createProfile: "Creează profil de autor",
    penName: "Pseudonim autor",
    email: "Email autor",
    saveProfile: "Salvează profil",
    myDrafts: "Proiectele Mele",
    newDraft: "Proiect Nou",
    publishToStore: "Publică pe Store",
    storeTitle: "Librăria Publică",
    storeIntro: "Explorează cărți scrise și publicate de alți cititori din comunitate. Descarcă-le gratuit direct pe raftul tău!",
    downloadBook: "Descarcă carte",
    likes: "Aprecieri",
    downloads: "Descărcări",
    quickStats: "Statistici Rapide",
    instructionsTitle: "Cum Funcționează Rețelele de Paginare?",
    instructionsText1: "1. Întoarcerea fizică a paginii: Faceți clic oriunde pe marginea dreaptă a cărții sau folosiți glisarea (swipe) pentru a deschide foaia următoare în stil 3D realist.",
    instructionsText2: "2. Căutare rapidă termeni: Apăsați pe tab-ul de căutare pentru a localiza instant orice pasaj într-un singur loc din toți indexii.",
    instructionsText3: "3. Atelierul autorului: Scrieți propria poveste, împărțiți-o pe capitole și publicați-o direct pe Librăria Store.",
    markPage: "Marchează",
    marked: "Marcat",
    adjustSettings: "Ajustează",
    settingsTitle: "Ajustare Aspect Vizual",
    colorTheme: "TEMĂ DE CULORI",
    fontFamilyLabel: "FONTUL TEXTULUI",
    fontSizeLabel: "MĂRIME FONT",
    lineSpacingLabel: "SPAȚIERE RÂNDURI",
    mobileHeightLabel: "ÎNĂLȚIME PAGINĂ",
    twoPageToggle: "Aspect Dublă Pagină",
    statusOn: "ACTIV",
    statusOff: "OPRIT",
    exploreBook: "EXPLOREAZĂ CARTEA",
    jumpToChapter: "Sari la acest capitol",
    noBookmarksTitle: "Niciun marcaj pe acest volum",
    noBookmarksTip: "Apasă pe butonul Marchează din bara de sus pentru a salva pagini importante.",
    readBook: "CITEȘTE",
    unread: "Necitită",
    authorPrefix: "de",
    endOfBook: "Sfârșitul cărții.",
    endOfChapter: "Sfârșitul capitolului.",
    startOfChapter: "Început de capitol.",
    allOptimized: "Totul este optimizat",
    appName: "ro-eBook Realist Reader",
    aiTranslationLabel: "TRADUCERE AI (necesită cheie Gemini)",
    twoPageSpreadActive: "ACTIV",
    twoPageSpreadOff: "OPRIT",
    appBrandName: "Lectura Realistă",
    appTagline: "Bibliotecă 3D & ePUB",
    pureUIBadge: "Interfață pură • Pure UI",
    customEpub: "CUSTOM EPUB",
    selectLanguage: "Alege limba / Select language",
    loadingLibrary: "Se încarcă rafturile bibliotecii locale...",
    emptyShelfHint: "Vă rugăm să importați prima voastră carte în format digital EPUB/TXT sau apăsați butonul de mai jos pentru a genera colecția demonstrativă de literatură clasică.",
    deleteBookmark: "Șterge marcaj",
    chShort: "CAP.",
    pageShort: "PAG.",
    noDescription: "Fără descriere disponibilă.",
    deleteBookTitle: "Șterge cartea",
    chapterShort: "Cap.",
    pageShortDot: "Pag.",
    uploadPanelTitle: "Adaugă o carte în bibliotecă",
    uploadPanelSubtitle: "Importă eBook-urile tale preferate în format digital sau inserează fragmente de text.",
    tabImportFile: "FIȘIER (.EPUB / .TXT / .PDF)",
    tabImportPaste: "LIPEȘTE TEXT SCRIPT",
    parsingChapters: "Se parsează capitolele și se creează paginile...",
    waitStructuring3D: "Așteptare structurare 3D",
    dragOrClickFile: "Trage fișierul sau apasă pentru a alege",
    supportedFormatsNote: "EPUB standard, documente PDF sau fișiere text (.txt)",
    formatEpub: "Format EPUB",
    formatEpubDesc: "Se importă structura nativă, capitolele, stilurile de bază și descrierile cărții.",
    formatPdf: "Document PDF",
    formatPdfDesc: "Extrage fluent textul din pagini și le compilează automat în capitole optimizate.",
    formatTxt: "Format TXT",
    formatTxtDesc: "Se detectează automat capitolele pe baza cuvântului „Capitolul” sau a spațierilor.",
    bookTitleLabel: "TITLUL CĂRȚII",
    bookTitlePlaceholder: "ex: Poezii de dragoste",
    authorOptionalPlaceholder: "ex: Mihai Eminescu (opțional)",
    contentLabel: "CONȚINUT / TEXTUL CĂRȚII",
    pasteContentPlaceholder: "Lipiți textul romanului sau poeziilor voastre aici...",
    pasteChapterTip: "Sfat: Structurați capitolele scriind „Capitolul I”, „Capitolul 1” etc. la începutul rândului pentru o segmentare optimă a meniului.",
    createBookBtn: "Creează cartea",
    localStorageNote: "Tot conținutul salvat rămâne stocat securizat în dispozitivul dumneavoastră.",
    unknownAuthor: "Autor Necunoscut",
    errorUnsupportedFormat: "Format nesuportat. Introduceți doar fișiere .epub, .txt sau .pdf.",
    errorReadTextFile: "Eroare la citirea fișierului text.",
    errorImportUnexpected: "Ceva neprevăzut s-a întâmplat în timpul importului.",
    errorFillTitleContent: "Vă rugăm să completați Titlul și Conținutul cărții.",
    errorProcessPastedText: "Nu s-a putut procesa textul introdus.",
    bookImportedSuccess: "a fost importată cu succes!",
    bookCreatedSuccess: "a fost creată din text cu succes!",
    registerAuthorTitle: "Înregistrare Autor Nou",
    authorCabinetTitle: "Cabinetul Autorului",
    registerAuthorDesc: "Înregistrează-ți pseudonimul unic și publică opere literare pe Store",
    loginAuthorDesc: "Conectează-te la contul tău de scriitor pentru a edita manuscrisele și proiectele",
    realNameLabel: "Nume Real",
    penNamePublicLabel: "Pseudonim de Autor (Nume Public)",
    penNameHint: "Acesta va fi tipărit pe coperta cărților pe care le publicați.",
    miniBioLabel: "Mini Biografie (Câteva cuvinte)",
    emailAddressLabel: "Adresă de Email",
    passwordPinLabel: "Parolă / Cod PIN",
    createAccountBtn: "CREEAZĂ CONT ȘI EXPUNE OPERE",
    enterCabinetBtn: "INTRĂ ÎN CABINETUL DE CREAȚIE",
    alreadyHaveAccount: "Ai deja cont creat? Intră aici",
    newAuthorSignup: "Scriitor debutant? Creează un cont de autor nou acum",
    errorEmailPassword: "Vă rugăm să introduceți emailul și codul PIN/parola.",
    errorNamePenName: "Vă rugăm să completați numele real și pseudonimul de autor.",
    errorEmailExists: "Acest email este deja înregistrat ca autor.",
    defaultBio: "Scriitor pasionat de povestiri și romane.",
    accountCreatedWelcome: "Cont creat cu succes! Bine ați venit în Cabinetul de Creație.",
    welcomeBackPrefix: "Bine ați revenit, ",
    errorNoAccount: "Nu există niciun cont înregistrat local. Bifați opțiunea din subsol pentru a crea un cont nou!",
    errorWrongCredentials: "Date de conectare incorecte. Reîncercați sau creați un cont nou.",
    errorDbQuery: "Eroare locală la interogarea bazei de date.",
    authorRegisteredLocal: "Autor înregistrat local",
    profileLinkedTo: "Profil legat de",
    enrolledOn: "Înrolat pe",
    logout: "Deconectare",
    logoutTitle: "Deconectare profil",
    createNewWork: "Creează o operă nouă",
    volumeTitleLabel: "Titlul volumului",
    volumeTitlePlaceholder: "Zbor frânt spre înălțimi",
    synopsisLabel: "Scurtă descriere / Sinopsis",
    synopsisPlaceholder: "Un roman de dragoste transpus într-un vechi conac transilvănean uitat de timp...",
    coverColorLabel: "Selecție Piele Copertă (Culoare)",
    coverStyleLabel: "Tipografie / Stil ornament copertă",
    createDraftBtn: "CREEAZĂ CIORNĂ CARTE (DRAFT)",
    yourSavedDrafts: "Ciornele tale salvate în lucru",
    noActiveDrafts: "Nu aveți nicio ciornă de carte activă.",
    noDraftsHint: "Completați formularul din stânga pentru a deschide un spațiu de scris literar privat dedicat operei voastre.",
    chaptersWritten: "capitole scrise",
    lastSaved: "Ultima salvare",
    writeNow: "scrie acum →",
    deleteDraftTitle: "Șterge ciornă",
    untitledDraft: "Fără titlu",
    defaultDraftDesc: "O lucrare splendidă.",
    draftCreatedMsg: "A fost creat un nou proiect de carte! Începeți scrierea mai jos.",
    defaultChapterTitle: "I. Introducere / Primul Capitol",
    defaultChapterContent: "Scrieți aici primele voastre rânduri dintr-o operă de neuitat...",
    chapterSavedMsg: "Capitolul și modificările ciornei au fost salvate cu succes!",
    errorSaveDraft: "Eroare la salvarea proiectului.",
    chapterN: "Capitolul",
    writeChapterHere: "Scrieți conținutul capitolului aici...",
    minOneChapter: "Cartea trebuie să aibă cel puțin un capitol.",
    confirmDeleteChapter: "Sigur doriți să ștergeți acest capitol? Această acțiune este ireversibilă.",
    confirmDeleteDraft: "Sigur doriți să ștergeți definitiv ciorna acestui volum? Progresul va fi șters local.",
    draftDeletedMsg: "Ciorna de volum a fost ștearsă.",
    fileImportedEditor: "a fost importat cu succes în editor! S-au adăugat paragrafele.",
    errorReadText: "Eroare la citirea textului.",
    pdfTxtOnlyImport: "Suportăm doar PDF și TXT pentru importul rapid în capitol.",
    errorImportText: "Eroare la importul textului.",
    confirmPublishChapters: "Vă rugăm să vă asigurați că toate capitolele au titluri și un conținut scris înainte de publicare.",
    publishSuccessPrefix: "Minunat! Titlul „",
    publishSuccessSuffix: "” a fost publicat pe Store. Alți cititori îl pot acum descărca din secțiunea Librărie Store!",
    errorPublish: "Eroare la publicare.",
    alreadyLiked: "Ați apreciat deja acest volum.",
    downloadSuccessPrefix: "Felicitări! Opera „",
    downloadSuccessMid: "” de ",
    downloadSuccessSuffix: " a fost descărcată și așezată pe raftul tău principal de lectură!",
    errorAddToLibrary: "Eroare la adăugarea volumului în bibliotecă.",
    editingDraftLabel: "Se editează ciorna romanului",
    backToCabinetTitle: "Înapoi la Cabinetul de Creație",
    saveDraftBtn: "Salvează Ciornă",
    chapterMapLabel: "Harta Capitolelor",
    addChapterBtn: "Adaugă",
    sectionN: "Secțiunea",
    untitledChapter: "Capitol fără titlu",
    deleteSectionTitle: "Șterge secțiune",
    currentChapterTitleLabel: "Titlul Capitolului Curent",
    chapterTitlePlaceholder: "Capitolul I: Rătăcirea",
    orUploadChapter: "Sau încarcă direct capitol (PDF sau TXT)",
    analyzingText: "Se analizează textul...",
    chooseFilePdfTxt: "Alege fișier (.pdf / .txt)",
    proseContentLabel: "CONȚINUT PROZĂ (HTML sau text simplu formatat cu paragrafe)",
    useSimpleParagraphs: "Folosiți paragrafe simple sau editorul liber",
    writeNovelHere: "Scrieți textul romanului aici...",
    charCount: "Număr caractere",
    estimatedWords: "Cuvinte estimate",
    autoSaveLocal: "Baza de date salvează automat ciornele local",
    editorTipTitle: "Sfatul Corectorului Lectura Realistă:",
    editorTipText: "Pentru o citire de elită pe ecranul 3D, asigurați rânduri lungi și paragrafe structurate. Puteți scrie text simplu — aplicația îl va formata automat la publicare.",
    communityStoreBadge: "Librăria Publică a Comunității",
    storeDiscoverTitle: "Descoperă manuscrise inedite publicate de autori reali",
    storeDiscoverDesc: "Bine ați venit pe piața liberă de povești! Explorați titlurile publicate de scriitori. Dacă găsiți o operă fascinantă, apăsați pe „Descarcă pe Raft” pentru a o instala în biblioteca voastră.",
    storeSearchPlaceholder: "Caută titlu, autor...",
    noSearchResults: "Nicio carte nu se asortează căutării",
    noSearchResultsHint: "Încearcați cuvinte generice sau vizitați Cabinetul de Autor pentru a publica aici.",
    noDescriptionByAuthor: "Nicio descriere definită de autor în cabinet.",
    downloadsLabel: "descărcări",
    likesLabel: "aprecieri",
    likeBookTitle: "Apreciază cartea",
    downloadToShelf: "DESCARCĂ PE RAFT",
    publishedOn: "Publicat",
    downloadThisBook: "Descarcă această operă pe raft",
    levelLabel: "Nivel",
    account: "Cont",
    accountPageTitle: "Contul Meu",
    accountPageSubtitle: "Biblioteca personală, progresul de lectură și marcajele tale.",
    accountLoginTitle: "Conectare Cititor",
    accountRegisterTitle: "Creare Cont Nou",
    accountLoginDesc: "Autentifică-te pentru a accesa biblioteca ta personală.",
    accountRegisterDesc: "Creează un cont local pentru a-ți organiza cărțile și marcajele.",
    accountNameLabel: "Nume",
    accountEmailLabel: "Email",
    accountPasswordLabel: "Parolă",
    accountLoginBtn: "INTRĂ ÎN CONT",
    accountRegisterBtn: "CREEAZĂ CONT",
    accountLogout: "Deconectare",
    accountAlreadyHave: "Ai deja cont? Conectează-te",
    accountNewUser: "Utilizator nou? Creează cont",
    accountWelcome: "Bine ai venit",
    accountJoined: "Membru din",
    accountLoginRequired: "Conectează-te pentru a vedea biblioteca ta.",
    accountInProgressSection: "Cărți în curs de lectură",
    accountNoInProgress: "Nicio carte începută încă.",
    accountContinueReading: "Continuă lectura",
    accountStatsBooks: "Volume",
    accountStatsProgress: "În progres",
    accountStatsBookmarks: "Marcaje",
    accountErrorMissing: "Completează toate câmpurile.",
    accountErrorEmailExists: "Acest email este deja înregistrat.",
    accountErrorWrongCredentials: "Email sau parolă incorectă.",
    accountErrorNoAccounts: "Nu există conturi. Creează unul nou.",
    homeGoToAccount: "Mergi la Contul Meu",
    homeLibraryMoved: "Cărțile tale, progresul și marcajele sunt acum în pagina Cont.",
  },
  en: {
    library: "Library",
    authorAtelier: "Author Atelier",
    store: "Store Shelf",
    importBook: "Import Book",
    howItWorks: "How it works",
    welcomeTitle: "Your literary universe beautifully crafted in",
    welcomeTitleAccent: "3D pages",
    welcomeSubtitle: "Welcome to the interactive reader dedicated to book lovers. Import EPUB or clean TXT formats, pick your favorite vintage parchment theme and enjoy the responsive paginating bend motions as you swipe.",
    importFirst: "IMPORT FIRST EBOOK",
    supportNote: "Optimized for tablets of any size and mobile devices.",
    ownBooks: "My Books",
    readingProgress: "In Progress",
    totalChapters: "Total Chapters",
    activeBookmarks: "Active Bookmarks",
    continueReading: "Continue Reading",
    deleteBookConfirm: "Are you sure you want to delete this book from your collection?",
    deleteBookmarkConfirm: "Are you sure you want to delete this bookmark?",
    chapters: "Contents",
    bookmarks: "Bookmarks",
    search: "Search",
    searchPlaceholder: "Search inside this book...",
    fontSize: "Font size",
    lineHeight: "Line height",
    layoutType: "Layout style",
    twoPageSpread: "Double-page",
    singlePage: "Single-page",
    noBooks: "No books in your library shelf yet.",
    dragDrop: "Drag and drop ebook files here, or click to browse",
    back: "Back",
    soundEffects: "Sound effects",
    closeReader: "Close",
    translateBook: "Translate",
    translateBookTitle: "AI Smart Translator",
    translateChapterBtn: "Translate to",
    translatingText: "Translating content via AI...",
    translationSuccess: "Chapter translated successfully!",
    translationError: "Translation failed. Please try again.",
    originalLanguage: "Original text (Book language)",
    viewOriginalText: "Show original text",
    translatedByAI: "Translated automatically with Gemini AI",
    aboutBook: "About Book",
    authorName: "Author",
    description: "Description",
    emptyBookmarks: "No bookmarks placed on the book pages.",
    addBookmarkTip: "Click the bookmark flag in the corner of the page while reading to save important sections.",
    bookmarksCount: "BOOKMARKS",
    chaptersCount: "CHAPTERS",
    searchResultsCount: "SEARCH RESULTS IN BOOK",
    searchNoResults: "No fragments found in the text.",
    searchAtLeast2: "Enter at least 2 characters to search...",
    secuEmptySearch: "Locate phrases or words",
    searchSecuTip: "Write a word or phrase in the box above to locate references and highlight them inside the book pages.",
    searchTitleHint: "search keywords",
    themeParchment: "Parchment",
    themeWarmPaper: "Warm Paper",
    themeSlateDark: "Slate Dark",
    themeMidnightVelvet: "Midnight Velvet",
    themeClassicWhite: "Classic White",
    aboutAuthor: "About Author Atelier",
    authorIntro: "Write and publish your own literature works. You can become the author of books sitting on the shelf!",
    createProfile: "Create Author Profile",
    penName: "Pen Name",
    email: "Author Email",
    saveProfile: "Save Profile",
    myDrafts: "My Drafts",
    newDraft: "New Draft",
    publishToStore: "Publish to Store",
    storeTitle: "Community Store",
    storeIntro: "Explore books written and published by other readers in the community. Download them for free onto your bookshelf!",
    downloadBook: "Download Book",
    likes: "Likes",
    downloads: "Downloads",
    quickStats: "Quick Stats",
    instructionsTitle: "How Paginating Works?",
    instructionsText1: "1. Physical sheet bending: Click anywhere on the right-hand page border or drag/swipe on touch-input devices to bend the page forward in a realistic 3D aesthetic.",
    instructionsText2: "2. Instant indexing search: Search keywords in the corresponding tab inside the sidebar to highlight them immediately.",
    instructionsText3: "3. Publish to community: Create original transcripts, organize chapters, and release them as custom releases to the public database Store.",
    markPage: "Bookmark",
    marked: "Bookmarked",
    adjustSettings: "Settings",
    settingsTitle: "Visual Appearance",
    colorTheme: "COLOR THEME",
    fontFamilyLabel: "TEXT FONT",
    fontSizeLabel: "FONT SIZE",
    lineSpacingLabel: "LINE SPACING",
    mobileHeightLabel: "PAGE HEIGHT",
    twoPageToggle: "Two-Page Spread",
    statusOn: "ON",
    statusOff: "OFF",
    exploreBook: "EXPLORE BOOK",
    jumpToChapter: "Jump to this chapter",
    noBookmarksTitle: "No bookmarks in this book",
    noBookmarksTip: "Press the Bookmark button in the top bar to save important pages.",
    readBook: "READ",
    unread: "Unread",
    authorPrefix: "by",
    endOfBook: "End of book.",
    endOfChapter: "End of chapter.",
    startOfChapter: "Start of chapter.",
    allOptimized: "All optimized",
    appName: "ro-eBook Realist Reader",
    aiTranslationLabel: "AI TRANSLATION (requires Gemini key)",
    twoPageSpreadActive: "ON",
    twoPageSpreadOff: "OFF",
    appBrandName: "Realist Reading",
    appTagline: "3D Library & ePUB",
    pureUIBadge: "Pure UI",
    customEpub: "CUSTOM EPUB",
    selectLanguage: "Select language",
    loadingLibrary: "Loading your local library shelves...",
    emptyShelfHint: "Please import your first digital EPUB/TXT book or press the button below to load the classic literature demo collection.",
    deleteBookmark: "Delete bookmark",
    chShort: "CH.",
    pageShort: "PG.",
    noDescription: "No description available.",
    deleteBookTitle: "Delete book",
    chapterShort: "Ch.",
    pageShortDot: "Pg.",
    uploadPanelTitle: "Add a book to your library",
    uploadPanelSubtitle: "Import your favorite eBooks digitally or paste text fragments.",
    tabImportFile: "FILE (.EPUB / .TXT / .PDF)",
    tabImportPaste: "PASTE TEXT SCRIPT",
    parsingChapters: "Parsing chapters and building pages...",
    waitStructuring3D: "Preparing 3D structure",
    dragOrClickFile: "Drag a file or click to browse",
    supportedFormatsNote: "Standard EPUB, PDF documents or text files (.txt)",
    formatEpub: "EPUB Format",
    formatEpubDesc: "Imports native structure, chapters, basic styles and book descriptions.",
    formatPdf: "PDF Document",
    formatPdfDesc: "Extracts text from pages and compiles it into optimized chapters.",
    formatTxt: "TXT Format",
    formatTxtDesc: "Automatically detects chapters based on the word \"Chapter\" or spacing.",
    bookTitleLabel: "BOOK TITLE",
    bookTitlePlaceholder: "e.g. Love Poems",
    authorOptionalPlaceholder: "e.g. John Doe (optional)",
    contentLabel: "CONTENT / BOOK TEXT",
    pasteContentPlaceholder: "Paste your novel or poems here...",
    pasteChapterTip: "Tip: Structure chapters by writing \"Chapter I\", \"Chapter 1\" etc. at the start of a line for optimal menu segmentation.",
    createBookBtn: "Create book",
    localStorageNote: "All saved content remains securely stored on your device.",
    unknownAuthor: "Unknown Author",
    errorUnsupportedFormat: "Unsupported format. Please use .epub, .txt or .pdf files only.",
    errorReadTextFile: "Error reading the text file.",
    errorImportUnexpected: "Something unexpected happened during import.",
    errorFillTitleContent: "Please fill in the Title and Book Content.",
    errorProcessPastedText: "Could not process the pasted text.",
    bookImportedSuccess: "was imported successfully!",
    bookCreatedSuccess: "was created from text successfully!",
    registerAuthorTitle: "New Author Registration",
    authorCabinetTitle: "Author Cabinet",
    registerAuthorDesc: "Register your unique pen name and publish literary works on the Store",
    loginAuthorDesc: "Log in to your writer account to edit manuscripts and projects",
    realNameLabel: "Real Name",
    penNamePublicLabel: "Author Pen Name (Public Name)",
    penNameHint: "This will be printed on the cover of books you publish.",
    miniBioLabel: "Mini Biography (A few words)",
    emailAddressLabel: "Email Address",
    passwordPinLabel: "Password / PIN Code",
    createAccountBtn: "CREATE ACCOUNT & PUBLISH WORKS",
    enterCabinetBtn: "ENTER CREATION CABINET",
    alreadyHaveAccount: "Already have an account? Log in here",
    newAuthorSignup: "New writer? Create an author account now",
    errorEmailPassword: "Please enter your email and PIN/password.",
    errorNamePenName: "Please fill in your real name and author pen name.",
    errorEmailExists: "This email is already registered as an author.",
    defaultBio: "A passionate writer of stories and novels.",
    accountCreatedWelcome: "Account created successfully! Welcome to the Creation Cabinet.",
    welcomeBackPrefix: "Welcome back, ",
    errorNoAccount: "No account registered locally. Check the option below to create a new account!",
    errorWrongCredentials: "Incorrect login details. Try again or create a new account.",
    errorDbQuery: "Local database query error.",
    authorRegisteredLocal: "Locally registered author",
    profileLinkedTo: "Profile linked to",
    enrolledOn: "Joined on",
    logout: "Log out",
    logoutTitle: "Log out profile",
    createNewWork: "Create a new work",
    volumeTitleLabel: "Volume title",
    volumeTitlePlaceholder: "Flight broken toward heights",
    synopsisLabel: "Short description / Synopsis",
    synopsisPlaceholder: "A love story set in a forgotten Transylvanian manor...",
    coverColorLabel: "Cover Leather Selection (Color)",
    coverStyleLabel: "Typography / Cover ornament style",
    createDraftBtn: "CREATE BOOK DRAFT",
    yourSavedDrafts: "Your saved drafts in progress",
    noActiveDrafts: "You have no active book drafts.",
    noDraftsHint: "Fill in the form on the left to open a private writing space for your work.",
    chaptersWritten: "chapters written",
    lastSaved: "Last saved",
    writeNow: "write now →",
    deleteDraftTitle: "Delete draft",
    untitledDraft: "Untitled",
    defaultDraftDesc: "A splendid work.",
    draftCreatedMsg: "A new book project was created! Start writing below.",
    defaultChapterTitle: "I. Introduction / First Chapter",
    defaultChapterContent: "Write your first lines of an unforgettable work here...",
    chapterSavedMsg: "Chapter and draft changes saved successfully!",
    errorSaveDraft: "Error saving the project.",
    chapterN: "Chapter",
    writeChapterHere: "Write the chapter content here...",
    minOneChapter: "The book must have at least one chapter.",
    confirmDeleteChapter: "Are you sure you want to delete this chapter? This action is irreversible.",
    confirmDeleteDraft: "Are you sure you want to permanently delete this volume draft? Progress will be erased locally.",
    draftDeletedMsg: "Volume draft was deleted.",
    fileImportedEditor: "was imported successfully into the editor! Paragraphs were added.",
    errorReadText: "Error reading the text.",
    pdfTxtOnlyImport: "We only support PDF and TXT for quick chapter import.",
    errorImportText: "Error importing text.",
    confirmPublishChapters: "Please ensure all chapters have titles and written content before publishing.",
    publishSuccessPrefix: "Wonderful! The title \"",
    publishSuccessSuffix: "\" was published on the Store. Other readers can now download it from the Store section!",
    errorPublish: "Publishing error.",
    alreadyLiked: "You have already liked this volume.",
    downloadSuccessPrefix: "Congratulations! The work \"",
    downloadSuccessMid: "\" by ",
    downloadSuccessSuffix: " was downloaded and placed on your main reading shelf!",
    errorAddToLibrary: "Error adding the volume to the library.",
    editingDraftLabel: "Editing novel draft",
    backToCabinetTitle: "Back to Creation Cabinet",
    saveDraftBtn: "Save Draft",
    chapterMapLabel: "Chapter Map",
    addChapterBtn: "Add",
    sectionN: "Section",
    untitledChapter: "Untitled chapter",
    deleteSectionTitle: "Delete section",
    currentChapterTitleLabel: "Current Chapter Title",
    chapterTitlePlaceholder: "Chapter I: Wandering",
    orUploadChapter: "Or upload chapter directly (PDF or TXT)",
    analyzingText: "Analyzing text...",
    chooseFilePdfTxt: "Choose file (.pdf / .txt)",
    proseContentLabel: "PROSE CONTENT (HTML or plain text with paragraphs)",
    useSimpleParagraphs: "Use simple paragraphs or the free editor",
    writeNovelHere: "Write the novel text here...",
    charCount: "Character count",
    estimatedWords: "Estimated words",
    autoSaveLocal: "Database automatically saves drafts locally",
    editorTipTitle: "Realist Reading Editor Tip:",
    editorTipText: "For elite 3D screen reading, use long structured paragraphs. You can write plain text — the app will format it automatically upon publishing.",
    communityStoreBadge: "Community Public Library",
    storeDiscoverTitle: "Discover unique manuscripts published by real authors",
    storeDiscoverDesc: "Welcome to the free story marketplace! Explore titles published by writers on the platform. If you find a fascinating work, press \"Download to Shelf\" to install it in your library.",
    storeSearchPlaceholder: "Search title, author...",
    noSearchResults: "No books match your search",
    noSearchResultsHint: "Try generic words or visit the Author Cabinet to become the first writer to publish here.",
    noDescriptionByAuthor: "No description defined by the author in the cabinet.",
    downloadsLabel: "downloads",
    likesLabel: "likes",
    likeBookTitle: "Like the book",
    downloadToShelf: "DOWNLOAD TO SHELF",
    publishedOn: "Published",
    downloadThisBook: "Download this work to shelf",
    levelLabel: "Level",
    account: "Account",
    accountPageTitle: "My Account",
    accountPageSubtitle: "Your personal library, reading progress and bookmarks.",
    accountLoginTitle: "Reader Login",
    accountRegisterTitle: "Create New Account",
    accountLoginDesc: "Sign in to access your personal library.",
    accountRegisterDesc: "Create a local account to organize your books and bookmarks.",
    accountNameLabel: "Name",
    accountEmailLabel: "Email",
    accountPasswordLabel: "Password",
    accountLoginBtn: "SIGN IN",
    accountRegisterBtn: "CREATE ACCOUNT",
    accountLogout: "Log out",
    accountAlreadyHave: "Already have an account? Sign in",
    accountNewUser: "New user? Create account",
    accountWelcome: "Welcome",
    accountJoined: "Member since",
    accountLoginRequired: "Sign in to view your library.",
    accountInProgressSection: "Books in progress",
    accountNoInProgress: "No books started yet.",
    accountContinueReading: "Continue reading",
    accountStatsBooks: "Volumes",
    accountStatsProgress: "In progress",
    accountStatsBookmarks: "Bookmarks",
    accountErrorMissing: "Please fill in all fields.",
    accountErrorEmailExists: "This email is already registered.",
    accountErrorWrongCredentials: "Incorrect email or password.",
    accountErrorNoAccounts: "No accounts found. Create a new one.",
    homeGoToAccount: "Go to My Account",
    homeLibraryMoved: "Your books, progress and bookmarks are now on the Account page.",
  },
  es: {
    library: "Biblioteca",
    authorAtelier: "Taller del Autor",
    store: "Librería Store",
    importBook: "Importar Libro",
    howItWorks: "Cómo funciona",
    welcomeTitle: "Tu universo literario plasmado en",
    welcomeTitleAccent: "páginas 3D",
    welcomeSubtitle: "Bienvenido al lector interactivo para los amantes de los libros. Importe EPUB o TXT, escoja su tema vintage de pergamino y disfrute de los movimientos realistas de flexión de página al deslizar.",
    importFirst: "IMPORTAR PRIMER EBOOK",
    supportNote: "Soporta tabletas de cualquier tamaño y teléfonos móviles.",
    ownBooks: "Tus Volúmenes",
    readingProgress: "En Progreso",
    totalChapters: "Capítulos Totales",
    activeBookmarks: "Marcadores Activos",
    continueReading: "Continuar Leyendo",
    deleteBookConfirm: "¿Seguro que desea eliminar este libro de su colección?",
    deleteBookmarkConfirm: "¿Seguro que desea eliminar este marcador?",
    chapters: "Índice",
    bookmarks: "Marcadores",
    search: "Buscar",
    searchPlaceholder: "Buscar en este libro...",
    fontSize: "Tamaño de letra",
    lineHeight: "Espaciado",
    layoutType: "Modo de Vista",
    twoPageSpread: "Páginas dobles",
    singlePage: "Página única",
    noBooks: "No hay libros en tu biblioteca.",
    dragDrop: "Arrastre los archivos aquí o haga clic para cargarlos",
    back: "Atrás",
    soundEffects: "Efectos de sonido",
    closeReader: "Cerrar",
    translateBook: "Traducir",
    translateBookTitle: "Traductor Inteligente de IA",
    translateChapterBtn: "Traducir al",
    translatingText: "Traduciendo contenido mediante IA...",
    translationSuccess: "¡Capítulo traducido con éxito!",
    translationError: "Error al traducir. Inténtelo de nuevo.",
    originalLanguage: "Texto original (Idioma del libro)",
    viewOriginalText: "Ver texto original",
    translatedByAI: "Traducido automáticamente con Gemini AI",
    aboutBook: "Acerca del Libro",
    authorName: "Autor",
    description: "Descripción",
    emptyBookmarks: "No se han colocado marcadores en el libro.",
    addBookmarkTip: "Haga clic en la cinta de marcadores en la esquina superior mientras lee para guardar párrafos importantes.",
    bookmarksCount: "MARCADORES",
    chaptersCount: "CAPÍTULOS",
    searchResultsCount: "RESULTADOS DE BÚSQUEDA",
    searchNoResults: "No se han encontrado pasajes.",
    searchAtLeast2: "Escriba un mínimo de 2 caracteres...",
    secuEmptySearch: "Localizar frases o palabras",
    searchSecuTip: "Escriba una frase en la casilla superior para encontrar coincidencias y resaltarlas en las hojas del libro.",
    searchTitleHint: "buscar palabras clave",
    themeParchment: "Pergamino",
    themeWarmPaper: "Papel Caliente",
    themeSlateDark: "Pizarra Oscura",
    themeMidnightVelvet: "Terciopelo Nocturno",
    themeClassicWhite: "Blanco Clásico",
    aboutAuthor: "Taller del Autor",
    authorIntro: "Escriba y publique sus propias creaciones literarias. ¡Conviértase en el autor de las obras que descansan en el estante!",
    createProfile: "Crear perfil de autor",
    penName: "Pseudónimo",
    email: "Email del autor",
    saveProfile: "Guardar Perfil",
    myDrafts: "Mis Proyectos",
    newDraft: "Nuevo Proyecto",
    publishToStore: "Publicar en Store",
    storeTitle: "Librería Comunitaria",
    storeIntro: "Explore libros creados y compartidos por la comunidad de lectores. ¡Descárguelos gratis a su estantería!",
    downloadBook: "Descargar",
    likes: "Me Gusta",
    downloads: "Descargas",
    quickStats: "Estadísticas",
    instructionsTitle: "¿Cómo funciona el doblado?",
    instructionsText1: "1. Doblamiento de página: Haga clic en los bordes de la derecha o arrastre en dispositivos táctiles para doblar la página dinámicamente con estética 3D.",
    instructionsText2: "2. Indexador de búsqueda: Localice términos y resáltelos al instante en las páginas del libro.",
    instructionsText3: "3. Redactar historias: Redacte novelas, organice capítulos y regístrelas gratis en la librería comunitaria pública.",
    markPage: "Marcar",
    marked: "Marcado",
    adjustSettings: "Ajustes",
    settingsTitle: "Apariencia Visual",
    colorTheme: "TEMA DE COLOR",
    fontFamilyLabel: "FUENTE DE TEXTO",
    fontSizeLabel: "TAMAÑO DE FUENTE",
    lineSpacingLabel: "ESPACIADO DE LÍNEA",
    mobileHeightLabel: "ALTURA DE PÁGINA",
    twoPageToggle: "Vista Doble Página",
    statusOn: "ACTIVO",
    statusOff: "INACTIVO",
    exploreBook: "EXPLORAR LIBRO",
    jumpToChapter: "Ir a este capítulo",
    noBookmarksTitle: "Sin marcadores en este libro",
    noBookmarksTip: "Pulsa el botón Marcar en la barra superior para guardar páginas importantes.",
    readBook: "LEER",
    unread: "No leído",
    authorPrefix: "por",
    endOfBook: "Fin del libro.",
    endOfChapter: "Fin del capítulo.",
    startOfChapter: "Inicio del capítulo.",
    allOptimized: "Todo optimizado",
    appName: "ro-eBook Realist Reader",
    aiTranslationLabel: "TRADUCCIÓN IA (requiere clave Gemini)",
    twoPageSpreadActive: "ACTIVO",
    twoPageSpreadOff: "INACTIVO",
    appBrandName: "Lectura Realista",
    appTagline: "Biblioteca 3D y ePUB",
    pureUIBadge: "Interfaz pura",
    customEpub: "EPUB PERSONALIZADO",
    selectLanguage: "Seleccionar idioma",
    loadingLibrary: "Cargando las estanterías de la biblioteca local...",
    emptyShelfHint: "Importe su primer libro digital EPUB/TXT o pulse el botón para cargar la colección demo de literatura clásica.",
    deleteBookmark: "Eliminar marcador",
    chShort: "CAP.",
    pageShort: "PÁG.",
    noDescription: "Sin descripción disponible.",
    deleteBookTitle: "Eliminar libro",
    chapterShort: "Cap.",
    pageShortDot: "Pág.",
    uploadPanelTitle: "Añadir un libro a la biblioteca",
    uploadPanelSubtitle: "Importe sus eBooks favoritos o pegue fragmentos de texto.",
    tabImportFile: "ARCHIVO (.EPUB / .TXT / .PDF)",
    tabImportPaste: "PEGAR TEXTO",
    parsingChapters: "Analizando capítulos y creando páginas...",
    waitStructuring3D: "Preparando estructura 3D",
    dragOrClickFile: "Arrastre un archivo o haga clic para elegir",
    supportedFormatsNote: "EPUB estándar, documentos PDF o archivos de texto (.txt)",
    formatEpub: "Formato EPUB",
    formatEpubDesc: "Importa estructura nativa, capítulos, estilos básicos y descripciones.",
    formatPdf: "Documento PDF",
    formatPdfDesc: "Extrae texto de las páginas y lo compila en capítulos optimizados.",
    formatTxt: "Formato TXT",
    formatTxtDesc: "Detecta automáticamente capítulos según la palabra \"Capítulo\" o espaciados.",
    bookTitleLabel: "TÍTULO DEL LIBRO",
    bookTitlePlaceholder: "ej: Poemas de amor",
    authorOptionalPlaceholder: "ej: Autor (opcional)",
    contentLabel: "CONTENIDO / TEXTO DEL LIBRO",
    pasteContentPlaceholder: "Pegue su novela o poemas aquí...",
    pasteChapterTip: "Consejo: Estructure capítulos escribiendo \"Capítulo I\", \"Capítulo 1\" etc. al inicio de la línea.",
    createBookBtn: "Crear libro",
    localStorageNote: "Todo el contenido guardado permanece almacenado de forma segura en su dispositivo.",
    unknownAuthor: "Autor Desconocido",
    errorUnsupportedFormat: "Formato no soportado. Use solo archivos .epub, .txt o .pdf.",
    errorReadTextFile: "Error al leer el archivo de texto.",
    errorImportUnexpected: "Algo inesperado ocurrió durante la importación.",
    errorFillTitleContent: "Complete el Título y el Contenido del libro.",
    errorProcessPastedText: "No se pudo procesar el texto pegado.",
    bookImportedSuccess: "fue importado con éxito!",
    bookCreatedSuccess: "fue creado desde texto con éxito!",
    registerAuthorTitle: "Registro de Autor Nuevo",
    authorCabinetTitle: "Gabinete del Autor",
    registerAuthorDesc: "Registre su seudónimo único y publique obras literarias en la Store",
    loginAuthorDesc: "Inicie sesión en su cuenta de escritor para editar manuscritos y proyectos",
    realNameLabel: "Nombre Real",
    penNamePublicLabel: "Seudónimo de Autor (Nombre Público)",
    penNameHint: "Este nombre aparecerá en la portada de los libros que publique.",
    miniBioLabel: "Mini Biografía (Unas palabras)",
    emailAddressLabel: "Dirección de Email",
    passwordPinLabel: "Contraseña / Código PIN",
    createAccountBtn: "CREAR CUENTA Y PUBLICAR OBRAS",
    enterCabinetBtn: "ENTRAR AL GABINETE DE CREACIÓN",
    alreadyHaveAccount: "¿Ya tiene cuenta? Entre aquí",
    newAuthorSignup: "¿Escritor debutante? Cree una cuenta de autor ahora",
    errorEmailPassword: "Introduzca su email y PIN/contraseña.",
    errorNamePenName: "Complete su nombre real y seudónimo de autor.",
    errorEmailExists: "Este email ya está registrado como autor.",
    defaultBio: "Escritor apasionado de historias y novelas.",
    accountCreatedWelcome: "¡Cuenta creada con éxito! Bienvenido al Gabinete de Creación.",
    welcomeBackPrefix: "Bienvenido de nuevo, ",
    errorNoAccount: "No hay cuenta registrada localmente. Marque la opción inferior para crear una cuenta nueva.",
    errorWrongCredentials: "Datos de acceso incorrectos. Inténtelo de nuevo o cree una cuenta nueva.",
    errorDbQuery: "Error local al consultar la base de datos.",
    authorRegisteredLocal: "Autor registrado localmente",
    profileLinkedTo: "Perfil vinculado a",
    enrolledOn: "Inscrito el",
    logout: "Cerrar sesión",
    logoutTitle: "Cerrar sesión del perfil",
    createNewWork: "Crear una obra nueva",
    volumeTitleLabel: "Título del volumen",
    volumeTitlePlaceholder: "Vuelo roto hacia las alturas",
    synopsisLabel: "Breve descripción / Sinopsis",
    synopsisPlaceholder: "Una historia de amor en un antiguo castillo olvidado...",
    coverColorLabel: "Selección de Piel de Portada (Color)",
    coverStyleLabel: "Tipografía / Estilo ornamental de portada",
    createDraftBtn: "CREAR BORRADOR DE LIBRO",
    yourSavedDrafts: "Sus borradores guardados en curso",
    noActiveDrafts: "No tiene borradores de libro activos.",
    noDraftsHint: "Complete el formulario de la izquierda para abrir un espacio de escritura privado.",
    chaptersWritten: "capítulos escritos",
    lastSaved: "Último guardado",
    writeNow: "escribir ahora →",
    deleteDraftTitle: "Eliminar borrador",
    untitledDraft: "Sin título",
    defaultDraftDesc: "Una obra espléndida.",
    draftCreatedMsg: "¡Se creó un nuevo proyecto de libro! Comience a escribir abajo.",
    defaultChapterTitle: "I. Introducción / Primer Capítulo",
    defaultChapterContent: "Escriba aquí sus primeras líneas de una obra inolvidable...",
    chapterSavedMsg: "¡Capítulo y cambios del borrador guardados con éxito!",
    errorSaveDraft: "Error al guardar el proyecto.",
    chapterN: "Capítulo",
    writeChapterHere: "Escriba el contenido del capítulo aquí...",
    minOneChapter: "El libro debe tener al menos un capítulo.",
    confirmDeleteChapter: "¿Seguro que desea eliminar este capítulo? Esta acción es irreversible.",
    confirmDeleteDraft: "¿Seguro que desea eliminar definitivamente este borrador? El progreso se borrará localmente.",
    draftDeletedMsg: "El borrador del volumen fue eliminado.",
    fileImportedEditor: "fue importado con éxito al editor. Se añadieron los párrafos.",
    errorReadText: "Error al leer el texto.",
    pdfTxtOnlyImport: "Solo admitimos PDF y TXT para importación rápida en capítulo.",
    errorImportText: "Error al importar el texto.",
    confirmPublishChapters: "Asegúrese de que todos los capítulos tengan títulos y contenido escrito antes de publicar.",
    publishSuccessPrefix: "¡Maravilloso! El título \"",
    publishSuccessSuffix: "\" fue publicado en la Store. ¡Otros lectores ya pueden descargarlo!",
    errorPublish: "Error al publicar.",
    alreadyLiked: "Ya ha apreciado este volumen.",
    downloadSuccessPrefix: "¡Felicitaciones! La obra \"",
    downloadSuccessMid: "\" de ",
    downloadSuccessSuffix: " fue descargada y colocada en su estantería principal de lectura.",
    errorAddToLibrary: "Error al añadir el volumen a la biblioteca.",
    editingDraftLabel: "Editando borrador de novela",
    backToCabinetTitle: "Volver al Gabinete de Creación",
    saveDraftBtn: "Guardar Borrador",
    chapterMapLabel: "Mapa de Capítulos",
    addChapterBtn: "Añadir",
    sectionN: "Sección",
    untitledChapter: "Capítulo sin título",
    deleteSectionTitle: "Eliminar sección",
    currentChapterTitleLabel: "Título del Capítulo Actual",
    chapterTitlePlaceholder: "Capítulo I: Deambulación",
    orUploadChapter: "O cargue capítulo directamente (PDF o TXT)",
    analyzingText: "Analizando texto...",
    chooseFilePdfTxt: "Elegir archivo (.pdf / .txt)",
    proseContentLabel: "CONTENIDO EN PROSA (HTML o texto plano con párrafos)",
    useSimpleParagraphs: "Use párrafos simples o el editor libre",
    writeNovelHere: "Escriba el texto de la novela aquí...",
    charCount: "Número de caracteres",
    estimatedWords: "Palabras estimadas",
    autoSaveLocal: "La base de datos guarda automáticamente los borradores localmente",
    editorTipTitle: "Consejo del Editor Lectura Realista:",
    editorTipText: "Para una lectura 3D de calidad, use párrafos largos y estructurados. Puede escribir texto simple — la app lo formateará automáticamente al publicar.",
    communityStoreBadge: "Librería Pública de la Comunidad",
    storeDiscoverTitle: "Descubra manuscritos únicos publicados por autores reales",
    storeDiscoverDesc: "¡Bienvenido al mercado libre de historias! Explore títulos publicados por escritores. Si encuentra una obra fascinante, pulse \"Descargar a Estantería\" para instalarla en su biblioteca.",
    storeSearchPlaceholder: "Buscar título, autor...",
    noSearchResults: "Ningún libro coincide con la búsqueda",
    noSearchResultsHint: "Pruebe palabras genéricas o visite el Gabinete del Autor para publicar aquí.",
    noDescriptionByAuthor: "Sin descripción definida por el autor en el gabinete.",
    downloadsLabel: "descargas",
    likesLabel: "me gusta",
    likeBookTitle: "Apreciar el libro",
    downloadToShelf: "DESCARGAR A ESTANTERÍA",
    publishedOn: "Publicado",
    downloadThisBook: "Descargar esta obra a la estantería",
    levelLabel: "Nivel",
    account: "Cuenta",
    accountPageTitle: "Mi Cuenta",
    accountPageSubtitle: "Tu biblioteca personal, progreso de lectura y marcadores.",
    accountLoginTitle: "Inicio de Sesión",
    accountRegisterTitle: "Crear Cuenta Nueva",
    accountLoginDesc: "Inicia sesión para acceder a tu biblioteca personal.",
    accountRegisterDesc: "Crea una cuenta local para organizar tus libros y marcadores.",
    accountNameLabel: "Nombre",
    accountEmailLabel: "Email",
    accountPasswordLabel: "Contraseña",
    accountLoginBtn: "ENTRAR",
    accountRegisterBtn: "CREAR CUENTA",
    accountLogout: "Cerrar sesión",
    accountAlreadyHave: "¿Ya tienes cuenta? Inicia sesión",
    accountNewUser: "¿Usuario nuevo? Crear cuenta",
    accountWelcome: "Bienvenido",
    accountJoined: "Miembro desde",
    accountLoginRequired: "Inicia sesión para ver tu biblioteca.",
    accountInProgressSection: "Libros en progreso",
    accountNoInProgress: "Ningún libro iniciado aún.",
    accountContinueReading: "Continuar leyendo",
    accountStatsBooks: "Volúmenes",
    accountStatsProgress: "En progreso",
    accountStatsBookmarks: "Marcadores",
    accountErrorMissing: "Complete todos los campos.",
    accountErrorEmailExists: "Este email ya está registrado.",
    accountErrorWrongCredentials: "Email o contraseña incorrectos.",
    accountErrorNoAccounts: "No hay cuentas. Cree una nueva.",
    homeGoToAccount: "Ir a Mi Cuenta",
    homeLibraryMoved: "Tus libros, progreso y marcadores están ahora en la página Cuenta.",
  },
  fr: {
    library: "Bibliothèque",
    authorAtelier: "Atelier d'Auteur",
    store: "Librairie Store",
    importBook: "Importer",
    howItWorks: "Comment ça marche",
    welcomeTitle: "Votre univers littéraire transposé en",
    welcomeTitleAccent: "pages 3D",
    welcomeSubtitle: "Bienvenue sur le lecteur interactif dédié aux amoureux du livre. Importez des fichiers EPUB ou TXT, choisissez votre thème de parchemin vintage et profitez des animations fluides de pliage de page lors du balayage de l'écran.",
    importFirst: "IMPORTER LE PREMIER LIVRE",
    supportNote: "Prend en charge les tablettes et smartphones de toutes tailles.",
    ownBooks: "Mes Livres",
    readingProgress: "En cours",
    totalChapters: "Chapitres Totaux",
    activeBookmarks: "Signets Actifs",
    continueReading: "Continuer la lecture",
    deleteBookConfirm: "Êtes-vous sûr de vouloir supprimer ce livre de votre étagère ?",
    deleteBookmarkConfirm: "Êtes-vous sûr de vouloir supprimer ce signet ?",
    chapters: "Sommaire",
    bookmarks: "Signets",
    search: "Rechercher",
    searchPlaceholder: "Chercher dans ce livre...",
    fontSize: "Taille de police",
    lineHeight: "Hauteur de ligne",
    layoutType: "Type d'affichage",
    twoPageSpread: "Double page",
    singlePage: "Simple page",
    noBooks: "Aucun livre dans votre bibliothèque.",
    dragDrop: "Glissez-déposez des fichiers ici ou cliquez pour parcourir",
    back: "Retour",
    soundEffects: "Effets sonores",
    closeReader: "Fermer",
    translateBook: "Traduire",
    translateBookTitle: "Traducteur Intelligent IA",
    translateChapterBtn: "Traduire en",
    translatingText: "Traduction du texte par IA...",
    translationSuccess: "Chapitre traduit avec succès !",
    translationError: "Erreur de traduction. Veuillez réessayer.",
    originalLanguage: "Texte original (Langue du livre)",
    viewOriginalText: "Afficher le texte original",
    translatedByAI: "Traduit automatiquement avec Gemini AI",
    aboutBook: "À propos du livre",
    authorName: "Auteur",
    description: "Description",
    emptyBookmarks: "Aucun signet ajouté sur les pages.",
    addBookmarkTip: "Cliquez sur l'onglet signet dans le coin de la page pendant votre lecture pour enregistrer des passages clés.",
    bookmarksCount: "SIGNETS",
    chaptersCount: "CHAPITRES",
    searchResultsCount: "NOTICES DE RECHERCHE",
    searchNoResults: "Aucun passage correspondant trouvé.",
    searchAtLeast2: "Saisissez au moins 2 caractères...",
    secuEmptySearch: "Localiser des phrases",
    searchSecuTip: "Tapez un mot ou une phrase ci-dessus pour situer et surligner dynamiquement les occurrences.",
    searchTitleHint: "mots-clés de recherche",
    themeParchment: "Parchemin",
    themeWarmPaper: "Papier Chaud",
    themeSlateDark: "Ardoise Sombre",
    themeMidnightVelvet: "Velours de Nuit",
    themeClassicWhite: "Blanc Classique",
    aboutAuthor: "Atelier des Auteurs",
    authorIntro: "Rédigez et publiez vos propres créations. Devenez l'auteur des romans imprimés sur nos étagères !",
    createProfile: "Créer un profil d'auteur",
    penName: "Pseudonyme",
    email: "E-mail de l'auteur",
    saveProfile: "Sauvegarder",
    myDrafts: "Mes Brouillons",
    newDraft: "Nouveau Projet",
    publishToStore: "Publier",
    storeTitle: "Librairie de la Communauté",
    storeIntro: "Découvrez des livres créés et partagés par d'autres lecteurs de la communauté. Téléchargez-les gratuitement !",
    downloadBook: "Télécharger",
    likes: "J'aime",
    downloads: "Téléchargements",
    quickStats: "Statistiques",
    instructionsTitle: "Comment fonctionne le pliage ?",
    instructionsText1: "1. Flexion de feuille réaliste : Cliquez sur les lisières droites ou balayez sur écran tactile pour courber la feuille en effet 3D exceptionnel.",
    instructionsText2: "2. Saisie de recherche : Retrouvez rapidement n'importe quelle citation et surlignez-la instantanément.",
    instructionsText3: "3. Éditeur de texte complet : Créez des récits originaux, divisez-les en chapitres et exportez-les gratuitement sur le Store.",
    markPage: "Marquer",
    marked: "Marqué",
    adjustSettings: "Paramétrer",
    settingsTitle: "Paramètres Visuels",
    colorTheme: "THÈME DE COULEUR",
    fontFamilyLabel: "POLICE DE TEXTE",
    fontSizeLabel: "TAILLE DE POLICE",
    lineSpacingLabel: "ESPACEMENT DE LIGNE",
    mobileHeightLabel: "HAUTEUR DE PAGE",
    twoPageToggle: "Double Page",
    statusOn: "ACTIVÉ",
    statusOff: "DÉSACTIVÉ",
    exploreBook: "EXPLORER LE LIVRE",
    jumpToChapter: "Aller à ce chapitre",
    noBookmarksTitle: "Pas de signets dans ce livre",
    noBookmarksTip: "Appuyez sur le bouton Marquer dans la barre supérieure pour sauvegarder des pages importantes.",
    readBook: "LIRE",
    unread: "Non lu",
    authorPrefix: "par",
    endOfBook: "Fin du livre.",
    endOfChapter: "Fin du chapitre.",
    startOfChapter: "Début du chapitre.",
    allOptimized: "Tout optimisé",
    appName: "ro-eBook Realist Reader",
    aiTranslationLabel: "TRADUCTION IA (clé Gemini requise)",
    twoPageSpreadActive: "ACTIVÉ",
    twoPageSpreadOff: "DÉSACTIVÉ",
    appBrandName: "Lecture Réaliste",
    appTagline: "Bibliothèque 3D & ePUB",
    pureUIBadge: "Interface pure",
    customEpub: "EPUB PERSONNALISÉ",
    selectLanguage: "Choisir la langue",
    loadingLibrary: "Chargement des étagères de la bibliothèque locale...",
    emptyShelfHint: "Importez votre premier livre numérique EPUB/TXT ou appuyez sur le bouton pour charger la collection démo de littérature classique.",
    deleteBookmark: "Supprimer le signet",
    chShort: "CH.",
    pageShort: "P.",
    noDescription: "Aucune description disponible.",
    deleteBookTitle: "Supprimer le livre",
    chapterShort: "Ch.",
    pageShortDot: "P.",
    uploadPanelTitle: "Ajouter un livre à la bibliothèque",
    uploadPanelSubtitle: "Importez vos eBooks préférés ou collez des fragments de texte.",
    tabImportFile: "FICHIER (.EPUB / .TXT / .PDF)",
    tabImportPaste: "COLLER DU TEXTE",
    parsingChapters: "Analyse des chapitres et création des pages...",
    waitStructuring3D: "Préparation de la structure 3D",
    dragOrClickFile: "Glissez un fichier ou cliquez pour parcourir",
    supportedFormatsNote: "EPUB standard, documents PDF ou fichiers texte (.txt)",
    formatEpub: "Format EPUB",
    formatEpubDesc: "Importe la structure native, les chapitres, les styles de base et les descriptions.",
    formatPdf: "Document PDF",
    formatPdfDesc: "Extrait le texte des pages et le compile en chapitres optimisés.",
    formatTxt: "Format TXT",
    formatTxtDesc: "Détecte automatiquement les chapitres selon le mot \"Chapitre\" ou les espacements.",
    bookTitleLabel: "TITRE DU LIVRE",
    bookTitlePlaceholder: "ex : Poèmes d'amour",
    authorOptionalPlaceholder: "ex : Auteur (optionnel)",
    contentLabel: "CONTENU / TEXTE DU LIVRE",
    pasteContentPlaceholder: "Collez votre roman ou vos poèmes ici...",
    pasteChapterTip: "Conseil : Structurez les chapitres en écrivant \"Chapitre I\", \"Chapitre 1\" etc. au début de la ligne.",
    createBookBtn: "Créer le livre",
    localStorageNote: "Tout le contenu sauvegardé reste stocké en sécurité sur votre appareil.",
    unknownAuthor: "Auteur Inconnu",
    errorUnsupportedFormat: "Format non pris en charge. Utilisez uniquement des fichiers .epub, .txt ou .pdf.",
    errorReadTextFile: "Erreur de lecture du fichier texte.",
    errorImportUnexpected: "Un événement inattendu s'est produit lors de l'importation.",
    errorFillTitleContent: "Veuillez remplir le Titre et le Contenu du livre.",
    errorProcessPastedText: "Impossible de traiter le texte collé.",
    bookImportedSuccess: "a été importé avec succès !",
    bookCreatedSuccess: "a été créé à partir du texte avec succès !",
    registerAuthorTitle: "Inscription Nouvel Auteur",
    authorCabinetTitle: "Cabinet de l'Auteur",
    registerAuthorDesc: "Enregistrez votre pseudonyme unique et publiez des œuvres littéraires sur le Store",
    loginAuthorDesc: "Connectez-vous à votre compte d'écrivain pour éditer manuscrits et projets",
    realNameLabel: "Nom Réel",
    penNamePublicLabel: "Pseudonyme d'Auteur (Nom Public)",
    penNameHint: "Ce nom sera imprimé sur la couverture des livres que vous publiez.",
    miniBioLabel: "Mini Biographie (Quelques mots)",
    emailAddressLabel: "Adresse Email",
    passwordPinLabel: "Mot de passe / Code PIN",
    createAccountBtn: "CRÉER UN COMPTE ET PUBLIER",
    enterCabinetBtn: "ENTRER DANS LE CABINET DE CRÉATION",
    alreadyHaveAccount: "Vous avez déjà un compte ? Connectez-vous ici",
    newAuthorSignup: "Nouvel écrivain ? Créez un compte auteur maintenant",
    errorEmailPassword: "Veuillez saisir votre email et PIN/mot de passe.",
    errorNamePenName: "Veuillez remplir votre nom réel et pseudonyme d'auteur.",
    errorEmailExists: "Cet email est déjà enregistré comme auteur.",
    defaultBio: "Écrivain passionné d'histoires et de romans.",
    accountCreatedWelcome: "Compte créé avec succès ! Bienvenue dans le Cabinet de Création.",
    welcomeBackPrefix: "Bon retour, ",
    errorNoAccount: "Aucun compte enregistré localement. Cochez l'option ci-dessous pour créer un nouveau compte !",
    errorWrongCredentials: "Identifiants incorrects. Réessayez ou créez un nouveau compte.",
    errorDbQuery: "Erreur locale lors de l'interrogation de la base de données.",
    authorRegisteredLocal: "Auteur enregistré localement",
    profileLinkedTo: "Profil lié à",
    enrolledOn: "Inscrit le",
    logout: "Déconnexion",
    logoutTitle: "Déconnexion du profil",
    createNewWork: "Créer une nouvelle œuvre",
    volumeTitleLabel: "Titre du volume",
    volumeTitlePlaceholder: "Vol brisé vers les hauteurs",
    synopsisLabel: "Brève description / Synopsis",
    synopsisPlaceholder: "Un roman d'amour dans un vieux manoir transylvanien oublié...",
    coverColorLabel: "Sélection Peau de Couverture (Couleur)",
    coverStyleLabel: "Typographie / Style ornement de couverture",
    createDraftBtn: "CRÉER UN BROUILLON DE LIVRE",
    yourSavedDrafts: "Vos brouillons sauvegardés en cours",
    noActiveDrafts: "Vous n'avez aucun brouillon de livre actif.",
    noDraftsHint: "Remplissez le formulaire à gauche pour ouvrir un espace d'écriture privé.",
    chaptersWritten: "chapitres écrits",
    lastSaved: "Dernière sauvegarde",
    writeNow: "écrire maintenant →",
    deleteDraftTitle: "Supprimer le brouillon",
    untitledDraft: "Sans titre",
    defaultDraftDesc: "Une œuvre splendide.",
    draftCreatedMsg: "Un nouveau projet de livre a été créé ! Commencez à écrire ci-dessous.",
    defaultChapterTitle: "I. Introduction / Premier Chapitre",
    defaultChapterContent: "Écrivez ici vos premières lignes d'une œuvre inoubliable...",
    chapterSavedMsg: "Chapitre et modifications du brouillon sauvegardés avec succès !",
    errorSaveDraft: "Erreur lors de la sauvegarde du projet.",
    chapterN: "Chapitre",
    writeChapterHere: "Écrivez le contenu du chapitre ici...",
    minOneChapter: "Le livre doit avoir au moins un chapitre.",
    confirmDeleteChapter: "Êtes-vous sûr de vouloir supprimer ce chapitre ? Cette action est irréversible.",
    confirmDeleteDraft: "Êtes-vous sûr de vouloir supprimer définitivement ce brouillon ? La progression sera effacée localement.",
    draftDeletedMsg: "Le brouillon du volume a été supprimé.",
    fileImportedEditor: "a été importé avec succès dans l'éditeur ! Les paragraphes ont été ajoutés.",
    errorReadText: "Erreur de lecture du texte.",
    pdfTxtOnlyImport: "Nous ne supportons que PDF et TXT pour l'import rapide dans un chapitre.",
    errorImportText: "Erreur lors de l'importation du texte.",
    confirmPublishChapters: "Assurez-vous que tous les chapitres ont des titres et du contenu écrit avant de publier.",
    publishSuccessPrefix: "Merveilleux ! Le titre « ",
    publishSuccessSuffix: " » a été publié sur le Store. D'autres lecteurs peuvent maintenant le télécharger !",
    errorPublish: "Erreur de publication.",
    alreadyLiked: "Vous avez déjà aimé ce volume.",
    downloadSuccessPrefix: "Félicitations ! L'œuvre « ",
    downloadSuccessMid: " » de ",
    downloadSuccessSuffix: " a été téléchargée et placée sur votre étagère principale de lecture !",
    errorAddToLibrary: "Erreur lors de l'ajout du volume à la bibliothèque.",
    editingDraftLabel: "Édition du brouillon de roman",
    backToCabinetTitle: "Retour au Cabinet de Création",
    saveDraftBtn: "Sauvegarder le Brouillon",
    chapterMapLabel: "Carte des Chapitres",
    addChapterBtn: "Ajouter",
    sectionN: "Section",
    untitledChapter: "Chapitre sans titre",
    deleteSectionTitle: "Supprimer la section",
    currentChapterTitleLabel: "Titre du Chapitre Actuel",
    chapterTitlePlaceholder: "Chapitre I : Errance",
    orUploadChapter: "Ou chargez un chapitre directement (PDF ou TXT)",
    analyzingText: "Analyse du texte...",
    chooseFilePdfTxt: "Choisir un fichier (.pdf / .txt)",
    proseContentLabel: "CONTENU EN PROSE (HTML ou texte simple avec paragraphes)",
    useSimpleParagraphs: "Utilisez des paragraphes simples ou l'éditeur libre",
    writeNovelHere: "Écrivez le texte du roman ici...",
    charCount: "Nombre de caractères",
    estimatedWords: "Mots estimés",
    autoSaveLocal: "La base de données sauvegarde automatiquement les brouillons localement",
    editorTipTitle: "Conseil de l'Éditeur Lecture Réaliste :",
    editorTipText: "Pour une lecture 3D de qualité, utilisez des paragraphes longs et structurés. Vous pouvez écrire du texte simple — l'application le formatera automatiquement à la publication.",
    communityStoreBadge: "Librairie Publique de la Communauté",
    storeDiscoverTitle: "Découvrez des manuscrits uniques publiés par de vrais auteurs",
    storeDiscoverDesc: "Bienvenue sur le marché libre des histoires ! Explorez les titres publiés par les écrivains. Si vous trouvez une œuvre fascinante, appuyez sur « Télécharger sur l'Étagère » pour l'installer dans votre bibliothèque.",
    storeSearchPlaceholder: "Chercher titre, auteur...",
    noSearchResults: "Aucun livre ne correspond à la recherche",
    noSearchResultsHint: "Essayez des mots génériques ou visitez le Cabinet de l'Auteur pour publier ici.",
    noDescriptionByAuthor: "Aucune description définie par l'auteur dans le cabinet.",
    downloadsLabel: "téléchargements",
    likesLabel: "j'aime",
    likeBookTitle: "Aimer le livre",
    downloadToShelf: "TÉLÉCHARGER SUR L'ÉTAGÈRE",
    publishedOn: "Publié",
    downloadThisBook: "Télécharger cette œuvre sur l'étagère",
    levelLabel: "Niveau",
    account: "Compte",
    accountPageTitle: "Mon Compte",
    accountPageSubtitle: "Votre bibliothèque personnelle, progrès de lecture et signets.",
    accountLoginTitle: "Connexion Lecteur",
    accountRegisterTitle: "Créer un Compte",
    accountLoginDesc: "Connectez-vous pour accéder à votre bibliothèque personnelle.",
    accountRegisterDesc: "Créez un compte local pour organiser vos livres et signets.",
    accountNameLabel: "Nom",
    accountEmailLabel: "Email",
    accountPasswordLabel: "Mot de passe",
    accountLoginBtn: "SE CONNECTER",
    accountRegisterBtn: "CRÉER UN COMPTE",
    accountLogout: "Déconnexion",
    accountAlreadyHave: "Déjà un compte ? Connectez-vous",
    accountNewUser: "Nouvel utilisateur ? Créer un compte",
    accountWelcome: "Bienvenue",
    accountJoined: "Membre depuis",
    accountLoginRequired: "Connectez-vous pour voir votre bibliothèque.",
    accountInProgressSection: "Livres en cours",
    accountNoInProgress: "Aucun livre commencé.",
    accountContinueReading: "Continuer la lecture",
    accountStatsBooks: "Volumes",
    accountStatsProgress: "En cours",
    accountStatsBookmarks: "Signets",
    accountErrorMissing: "Remplissez tous les champs.",
    accountErrorEmailExists: "Cet email est déjà enregistré.",
    accountErrorWrongCredentials: "Email ou mot de passe incorrect.",
    accountErrorNoAccounts: "Aucun compte. Créez-en un nouveau.",
    homeGoToAccount: "Aller à Mon Compte",
    homeLibraryMoved: "Vos livres, progrès et signets sont maintenant sur la page Compte.",
  },
  it: {
    library: "Libreria",
    authorAtelier: "Atelier Autore",
    store: "Libreria Store",
    importBook: "Importa Libro",
    howItWorks: "Come funziona",
    welcomeTitle: "Il tuo universo letterario tradotto in",
    welcomeTitleAccent: "pagine 3D",
    welcomeSubtitle: "Benvenuto nel lettore interattivo per la lettura di libri digitali. Importa Epub o TXT, scegli il tuo tema pergamena vintage classico e sperimenta i passaggi di pagina reali ed evocativi.",
    importFirst: "IMPORTA IL PRIMO EBOOK",
    supportNote: "Ottimizzato per tablet e telefoni cellulari di qualsiasi dimensione.",
    ownBooks: "Miei Volumi",
    readingProgress: "In Corso",
    totalChapters: "Capitoli Totali",
    activeBookmarks: "Segnalibri Attivi",
    continueReading: "Continua Lettura",
    deleteBookConfirm: "Sei sicuro di voler eliminare questo libro dalla tua collezione?",
    deleteBookmarkConfirm: "Sei sicuro di voler rimuovere questo segnalibro?",
    chapters: "Indice",
    bookmarks: "Segnalibri",
    search: "Cerca",
    searchPlaceholder: "Cerca all'interno del libro...",
    fontSize: "Grandezza testo",
    lineHeight: "Altezza riga",
    layoutType: "Visualizzazione",
    twoPageSpread: "Doppia pagina",
    singlePage: "Pagina singola",
    noBooks: "La tua biblioteca è vuota.",
    dragDrop: "Trascina i file epub o txt qui o fai clic per caricarli",
    back: "Indietro",
    soundEffects: "Effetti sonori",
    closeReader: "Chiudi",
    translateBook: "Traduci",
    translateBookTitle: "Traduttore Intelligente IA",
    translateChapterBtn: "Traduci in",
    translatingText: "Traduzione del testo in corso tramite IA...",
    translationSuccess: "Capitolo tradotto con successo!",
    translationError: "Errore di traduzione. Riprova.",
    originalLanguage: "Testo original (Lingua del libro)",
    viewOriginalText: "Mostra testo originale",
    translatedByAI: "Tradotto automaticamente con Gemini AI",
    aboutBook: "Dettagli del Libro",
    authorName: "Autore",
    description: "Descrizione",
    emptyBookmarks: "Nessun segnalibro aggiunto su questo libro.",
    addBookmarkTip: "Clicca la fascetta del segnalibro sull'angolo in alto mentre leggi per salvare i passaggi preferiti.",
    bookmarksCount: "SEGNALIBRI",
    chaptersCount: "CAPITOLI",
    searchResultsCount: "RISULTATI DELLA RICERCA",
    searchNoResults: "Nessuna corrispondenza trovata.",
    searchAtLeast2: "Digita almeno 2 caratteri...",
    secuEmptySearch: "Trova espressioni o parole",
    searchSecuTip: "Inserisci un termine di ricerca per visualizzare ed evidenziare tutti i riferimenti significativi.",
    searchTitleHint: "parole chiave",
    themeParchment: "Pergamena",
    themeWarmPaper: "Carta Calda",
    themeSlateDark: "Ardesia Scuro",
    themeMidnightVelvet: "Velluto Notturno",
    themeClassicWhite: "Bianco Classico",
    aboutAuthor: "Laboratorio Scrittura",
    authorIntro: "Crea e pubblica le tue opere letterarie. Diventa l'autore dei sogni visibili in biblioteca!",
    createProfile: "Crea profilo autore",
    penName: "Pseudonimo",
    email: "Email autore",
    saveProfile: "Salva Profilo",
    myDrafts: "I Miei Progetti",
    newDraft: "Nuovo Progetto",
    publishToStore: "Pubblica",
    storeTitle: "Negozio Comunitario",
    storeIntro: "Explore books written and published by other readers in the community. Download them for free onto your bookshelf!",
    downloadBook: "Scarica",
    likes: "Mi Piace",
    downloads: "Download",
    quickStats: "Statistiche",
    instructionsTitle: "Come funziona la paginazione interattiva?",
    instructionsText1: "1. Piegatura del foglio: Clicca sul margine destro o trascina per sfogliare realisticamente i fogli in 3D.",
    instructionsText2: "2. Ricerca termini: Cerca qualsiasi termine all'interno della barra laterale per evidenziarlo all'istante.",
    instructionsText3: "3. Atelier scrittore: Componi le tue opere personali suddivise in capitoli e caricale nel negozio online.",
    markPage: "Segna",
    marked: "Segnato",
    adjustSettings: "Imposta",
    settingsTitle: "Impostazioni Visive",
    colorTheme: "TEMA COLORE",
    fontFamilyLabel: "FONT TESTO",
    fontSizeLabel: "DIMENSIONE FONT",
    lineSpacingLabel: "SPAZIATURA RIGHE",
    mobileHeightLabel: "ALTEZZA PAGINA",
    twoPageToggle: "Doppia Pagina",
    statusOn: "ATTIVO",
    statusOff: "DISATTIVO",
    exploreBook: "ESPLORA IL LIBRO",
    jumpToChapter: "Vai a questo capitolo",
    noBookmarksTitle: "Nessun segnalibro in questo libro",
    noBookmarksTip: "Premi il pulsante Segna nella barra superiore per salvare le pagine importanti.",
    readBook: "LEGGI",
    unread: "Non letto",
    authorPrefix: "di",
    endOfBook: "Fine del libro.",
    endOfChapter: "Fine del capitolo.",
    startOfChapter: "Inizio del capitolo.",
    allOptimized: "Tutto ottimizzato",
    appName: "ro-eBook Realist Reader",
    aiTranslationLabel: "TRADUZIONE IA (richiede chiave Gemini)",
    twoPageSpreadActive: "ATTIVO",
    twoPageSpreadOff: "DISATTIVO",
    appBrandName: "Lettura Realistica",
    appTagline: "Libreria 3D & ePUB",
    pureUIBadge: "Interfaccia pura",
    customEpub: "EPUB PERSONALIZATO",
    selectLanguage: "Seleziona lingua",
    loadingLibrary: "Caricamento degli scaffali della libreria locale...",
    emptyShelfHint: "Importa il tuo primo libro digitale EPUB/TXT o premi il pulsante per caricare la collezione demo di letteratura classica.",
    deleteBookmark: "Elimina segnalibro",
    chShort: "CAP.",
    pageShort: "PAG.",
    noDescription: "Nessuna descrizione disponibile.",
    deleteBookTitle: "Elimina libro",
    chapterShort: "Cap.",
    pageShortDot: "Pag.",
    uploadPanelTitle: "Aggiungi un libro alla libreria",
    uploadPanelSubtitle: "Importa i tuoi eBook preferiti o incolla frammenti di testo.",
    tabImportFile: "FILE (.EPUB / .TXT / .PDF)",
    tabImportPaste: "INCOLLA TESTO",
    parsingChapters: "Analisi dei capitoli e creazione delle pagine...",
    waitStructuring3D: "Preparazione struttura 3D",
    dragOrClickFile: "Trascina un file o clicca per scegliere",
    supportedFormatsNote: "EPUB standard, documenti PDF o file di testo (.txt)",
    formatEpub: "Formato EPUB",
    formatEpubDesc: "Importa struttura nativa, capitoli, stili di base e descrizioni.",
    formatPdf: "Documento PDF",
    formatPdfDesc: "Estrae il testo dalle pagine e lo compila in capitoli ottimizzati.",
    formatTxt: "Formato TXT",
    formatTxtDesc: "Rileva automaticamente i capitoli in base alla parola \"Capitolo\" o agli spazi.",
    bookTitleLabel: "TITOLO DEL LIBRO",
    bookTitlePlaceholder: "es: Poesie d'amore",
    authorOptionalPlaceholder: "es: Autore (opzionale)",
    contentLabel: "CONTENUTO / TESTO DEL LIBRO",
    pasteContentPlaceholder: "Incolla qui il tuo romanzo o le tue poesie...",
    pasteChapterTip: "Suggerimento: Struttura i capitoli scrivendo \"Capitolo I\", \"Capitolo 1\" ecc. all'inizio della riga.",
    createBookBtn: "Crea libro",
    localStorageNote: "Tutto il contenuto salvato rimane archiviato in sicurezza sul tuo dispositivo.",
    unknownAuthor: "Autore Sconosciuto",
    errorUnsupportedFormat: "Formato non supportato. Usa solo file .epub, .txt o .pdf.",
    errorReadTextFile: "Errore nella lettura del file di testo.",
    errorImportUnexpected: "Qualcosa di inaspettato è accaduto durante l'importazione.",
    errorFillTitleContent: "Compila il Titolo e il Contenuto del libro.",
    errorProcessPastedText: "Impossibile elaborare il testo incollato.",
    bookImportedSuccess: "è stato importato con successo!",
    bookCreatedSuccess: "è stato creato dal testo con successo!",
    registerAuthorTitle: "Registrazione Nuovo Autore",
    authorCabinetTitle: "Cabinet dell'Autore",
    registerAuthorDesc: "Registra il tuo pseudonimo unico e pubblica opere letterarie sullo Store",
    loginAuthorDesc: "Accedi al tuo account di scrittore per modificare manoscritti e progetti",
    realNameLabel: "Nome Reale",
    penNamePublicLabel: "Pseudonimo Autore (Nome Pubblico)",
    penNameHint: "Questo nome sarà stampato sulla copertina dei libri che pubblichi.",
    miniBioLabel: "Mini Biografia (Poche parole)",
    emailAddressLabel: "Indirizzo Email",
    passwordPinLabel: "Password / Codice PIN",
    createAccountBtn: "CREA ACCOUNT E PUBBLICA OPERE",
    enterCabinetBtn: "ENTRA NEL CABINET DI CREAZIONE",
    alreadyHaveAccount: "Hai già un account? Accedi qui",
    newAuthorSignup: "Scrittore debuttante? Crea un account autore ora",
    errorEmailPassword: "Inserisci email e PIN/password.",
    errorNamePenName: "Compila il nome reale e il pseudonimo dell'autore.",
    errorEmailExists: "Questa email è già registrata come autore.",
    defaultBio: "Scrittore appassionato di storie e romanzi.",
    accountCreatedWelcome: "Account creato con successo! Benvenuto nel Cabinet di Creazione.",
    welcomeBackPrefix: "Bentornato, ",
    errorNoAccount: "Nessun account registrato localmente. Seleziona l'opzione in basso per creare un nuovo account!",
    errorWrongCredentials: "Credenziali errate. Riprova o crea un nuovo account.",
    errorDbQuery: "Errore locale nell'interrogazione del database.",
    authorRegisteredLocal: "Autore registrato localmente",
    profileLinkedTo: "Profilo collegato a",
    enrolledOn: "Iscritto il",
    logout: "Esci",
    logoutTitle: "Esci dal profilo",
    createNewWork: "Crea una nuova opera",
    volumeTitleLabel: "Titolo del volume",
    volumeTitlePlaceholder: "Volo spezzato verso le altezze",
    synopsisLabel: "Breve descrizione / Sinossi",
    synopsisPlaceholder: "Un romanzo d'amore in un antico maniero dimenticato...",
    coverColorLabel: "Selezione Pelle Copertina (Colore)",
    coverStyleLabel: "Tipografia / Stile ornamento copertina",
    createDraftBtn: "CREA BOZZA LIBRO",
    yourSavedDrafts: "Le tue bozze salvate in corso",
    noActiveDrafts: "Non hai bozze di libro attive.",
    noDraftsHint: "Compila il modulo a sinistra per aprire uno spazio di scrittura privato.",
    chaptersWritten: "capitoli scritti",
    lastSaved: "Ultimo salvataggio",
    writeNow: "scrivi ora →",
    deleteDraftTitle: "Elimina bozza",
    untitledDraft: "Senza titolo",
    defaultDraftDesc: "Un'opera splendida.",
    draftCreatedMsg: "È stato creato un nuovo progetto di libro! Inizia a scrivere qui sotto.",
    defaultChapterTitle: "I. Introduzione / Primo Capitolo",
    defaultChapterContent: "Scrivi qui le tue prime righe di un'opera indimenticabile...",
    chapterSavedMsg: "Capitolo e modifiche della bozza salvati con successo!",
    errorSaveDraft: "Errore nel salvataggio del progetto.",
    chapterN: "Capitolo",
    writeChapterHere: "Scrivi il contenuto del capitolo qui...",
    minOneChapter: "Il libro deve avere almeno un capitolo.",
    confirmDeleteChapter: "Sei sicuro di voler eliminare questo capitolo? Questa azione è irreversibile.",
    confirmDeleteDraft: "Sei sicuro di voler eliminare definitivamente questa bozza? Il progresso sarà cancellato localmente.",
    draftDeletedMsg: "La bozza del volume è stata eliminata.",
    fileImportedEditor: "è stato importato con successo nell'editor! I paragrafi sono stati aggiunti.",
    errorReadText: "Errore nella lettura del testo.",
    pdfTxtOnlyImport: "Supportiamo solo PDF e TXT per l'import rapido nel capitolo.",
    errorImportText: "Errore nell'importazione del testo.",
    confirmPublishChapters: "Assicurati che tutti i capitoli abbiano titoli e contenuto scritto prima di pubblicare.",
    publishSuccessPrefix: "Meraviglioso! Il titolo \"",
    publishSuccessSuffix: "\" è stato pubblicato sullo Store. Altri lettori possono ora scaricarlo!",
    errorPublish: "Errore di pubblicazione.",
    alreadyLiked: "Hai già apprezzato questo volume.",
    downloadSuccessPrefix: "Congratulazioni! L'opera \"",
    downloadSuccessMid: "\" di ",
    downloadSuccessSuffix: " è stata scaricata e posizionata sul tuo scaffale principale di lettura!",
    errorAddToLibrary: "Errore nell'aggiunta del volume alla libreria.",
    editingDraftLabel: "Modifica bozza romanzo",
    backToCabinetTitle: "Torna al Cabinet di Creazione",
    saveDraftBtn: "Salva Bozza",
    chapterMapLabel: "Mappa dei Capitoli",
    addChapterBtn: "Aggiungi",
    sectionN: "Sezione",
    untitledChapter: "Capitolo senza titolo",
    deleteSectionTitle: "Elimina sezione",
    currentChapterTitleLabel: "Titolo del Capitolo Corrente",
    chapterTitlePlaceholder: "Capitolo I: Erranza",
    orUploadChapter: "Oppure carica capitolo direttamente (PDF o TXT)",
    analyzingText: "Analisi del testo...",
    chooseFilePdfTxt: "Scegli file (.pdf / .txt)",
    proseContentLabel: "CONTENUTO IN PROSA (HTML o testo semplice con paragrafi)",
    useSimpleParagraphs: "Usa paragrafi semplici o l'editor libero",
    writeNovelHere: "Scrivi il testo del romanzo qui...",
    charCount: "Numero di caratteri",
    estimatedWords: "Parole stimate",
    autoSaveLocal: "Il database salva automaticamente le bozze localmente",
    editorTipTitle: "Consiglio dell'Editor Lettura Realistica:",
    editorTipText: "Per una lettura 3D di qualità, usa paragrafi lunghi e strutturati. Puoi scrivere testo semplice — l'app lo formatterà automaticamente alla pubblicazione.",
    communityStoreBadge: "Libreria Pubblica della Comunità",
    storeDiscoverTitle: "Scopri manoscritti unici pubblicati da autori reali",
    storeDiscoverDesc: "Benvenuto nel mercato libero delle storie! Esplora i titoli pubblicati dagli scrittori. Se trovi un'opera affascinante, premi \"Scarica sullo Scaffale\" per installarla nella tua libreria.",
    storeSearchPlaceholder: "Cerca titolo, autore...",
    noSearchResults: "Nessun libro corrisponde alla ricerca",
    noSearchResultsHint: "Prova parole generiche o visita il Cabinet dell'Autore per pubblicare qui.",
    noDescriptionByAuthor: "Nessuna descrizione definita dall'autore nel cabinet.",
    downloadsLabel: "download",
    likesLabel: "mi piace",
    likeBookTitle: "Apprezza il libro",
    downloadToShelf: "SCARICA SULLO SCAFFALE",
    publishedOn: "Pubblicato",
    downloadThisBook: "Scarica quest'opera sullo scaffale",
    levelLabel: "Livello",
    account: "Account",
    accountPageTitle: "Il Mio Account",
    accountPageSubtitle: "La tua libreria personale, progresso di lettura e segnalibri.",
    accountLoginTitle: "Accesso Lettore",
    accountRegisterTitle: "Crea Nuovo Account",
    accountLoginDesc: "Accedi per vedere la tua libreria personale.",
    accountRegisterDesc: "Crea un account locale per organizzare libri e segnalibri.",
    accountNameLabel: "Nome",
    accountEmailLabel: "Email",
    accountPasswordLabel: "Password",
    accountLoginBtn: "ACCEDI",
    accountRegisterBtn: "CREA ACCOUNT",
    accountLogout: "Esci",
    accountAlreadyHave: "Hai già un account? Accedi",
    accountNewUser: "Nuovo utente? Crea account",
    accountWelcome: "Benvenuto",
    accountJoined: "Membro dal",
    accountLoginRequired: "Accedi per vedere la tua libreria.",
    accountInProgressSection: "Libri in corso",
    accountNoInProgress: "Nessun libro iniziato.",
    accountContinueReading: "Continua lettura",
    accountStatsBooks: "Volumi",
    accountStatsProgress: "In corso",
    accountStatsBookmarks: "Segnalibri",
    accountErrorMissing: "Compila tutti i campi.",
    accountErrorEmailExists: "Questa email è già registrata.",
    accountErrorWrongCredentials: "Email o password errati.",
    accountErrorNoAccounts: "Nessun account. Creane uno nuovo.",
    homeGoToAccount: "Vai al Mio Account",
    homeLibraryMoved: "I tuoi libri, progresso e segnalibri sono ora nella pagina Account.",
  },
};

// Simple global listener-based store for language updates so all components automatically re-render when language changes
let currentLang: LanguageCode = (localStorage.getItem("ebook-reader-lang") as LanguageCode) || "ro";
const listeners = new Set<() => void>();

export function getAppLanguage(): LanguageCode {
  return currentLang;
}

export function setAppLanguage(lang: LanguageCode) {
  currentLang = lang;
  localStorage.setItem("ebook-reader-lang", lang);
  listeners.forEach((l) => l());
}

export function useTranslation() {
  const [lang, setLang] = useState<LanguageCode>(currentLang);

  useEffect(() => {
    const handleUpdate = () => {
      setLang(currentLang);
    };
    listeners.add(handleUpdate);
    return () => {
      listeners.delete(handleUpdate);
    };
  }, []);

  const t = (key: keyof typeof UI_TRANSLATIONS["ro"]) => {
    return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS["ro"][key];
  };

  return { t, currentLanguage: lang, setLanguage: setAppLanguage, languages: LANGUAGES };
}
