import { useState, useEffect } from "react";

export type LanguageCode = "ro" | "en" | "es" | "fr" | "it";

export interface Language {
  code: LanguageCode;
  label: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "ro", label: "Română", flag: "🇷🇴" },
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
];

export const UI_TRANSLATIONS = {
  ro: {
    library: "Bibliotecă",
    authorAtelier: "Atelier Autor",
    store: "Librărie Store",
    importBook: "Importă Carte",
    howItWorks: "Cum funcționează",
    welcomeTitle: "Universul tău literar transpus în",
    welcomeTitleAccent: "pagini curate 3D",
    welcomeSubtitle: "Bine ați venit în cititorul interactiv dedicat pasionaților de carte. Importați romane în format ePUB sau fișiere TXT curat formatate, alegeți-vă tema vintage pergament perfect adaptată lecturii nocturne și bucurați-vă de mișcarea fizică realistă a paginilor care se îndoaie sub gestul de swipe.",
    importFirst: "IMPORTĂ PRIMUL EBOOK",
    supportNote: "Suportă tablete de orice mărime și telefoane mobile.",
    ownBooks: "Volume proprii",
    readingProgress: "Cărți în progres",
    totalChapters: "Capitole totale",
    activeBookmarks: "Marcaje active",
    continueReading: "Continuă lectura",
    deleteBookConfirm: "Sigur doriți să ștergeți această carte din colecția dumneavoastră?",
    deleteBookmarkConfirm: "Sigur doriți să ștergeți acest marcaj?",
    chapters: "Cuprins",
    bookmarks: "Marcaje",
    search: "Caută",
    searchPlaceholder: "Caută în această carte...",
    fontSize: "Mărime font",
    lineHeight: "Înălțime rând",
    layoutType: "Mod afișare",
    twoPageSpread: "Pagini duble",
    singlePage: "Pagini simple",
    noBooks: "Nu aveți nicio carte în bibliotecă.",
    dragDrop: "Trageți și plasați fișierele aici sau dați click pentru selectare",
    back: "Înapoi",
    soundEffects: "Efecte de sunet",
    closeReader: "Închide",
    translateBook: "Traducere Text",
    translateBookTitle: "Traducere Inteligentă AI",
    translateChapterBtn: "Tradu în",
    translatingText: "Se traduce textul prin AI...",
    translationSuccess: "Capitolul a fost tradus cu succes!",
    translationError: "Eroare la traducere. Reîncercați.",
    originalLanguage: "Text original (Limba cărții)",
    viewOriginalText: "Vezi textul original",
    translatedByAI: "Tradus automat cu Gemini AI",
    aboutBook: "Despre carte",
    authorName: "Nume autor",
    description: "Descriere",
    emptyBookmarks: "Niciun marcaj adăugat pe filele cărții.",
    addBookmarkTip: "Faceți clic pe steagul de marcaj din colțul paginii în timp ce citiți pentru a nota paragrafe importante.",
    bookmarksCount: "MARCAJE",
    chaptersCount: "CAPITOLE",
    searchResultsCount: "REZULTATE ÎN TOATĂ CARTEA",
    searchNoResults: "Niciun fragment găsit în text.",
    searchAtLeast2: "Scrie minimum 2 caractere pentru a lansa căutarea...",
    secuEmptySearch: "Localizează expresii sau cuvinte",
    searchSecuTip: "Scrie un cuvânt sau o propoziție în caseta de mai sus pentru a găsi toate fragmentele purtătoare și a le evidenția dinamic pe foile cărții.",
    searchTitleHint: "caută cuvinte cheie",
    themeParchment: "Pergament",
    themeWarmPaper: "Hârtie caldă",
    themeSlateDark: "Ardezie închis",
    themeMidnightVelvet: "Catifea de noapte",
    themeClassicWhite: "Alb clasic",
    aboutAuthor: "Despre Atelierul de Autor",
    authorIntro: "Scrieți și publicați propriile creații literare. Puteți deveni chiar dumneavoastră autorul operelor de pe raft!",
    createProfile: "Creează profil de autor",
    penName: "Pseudonim autor",
    email: "Email autor",
    saveProfile: "Salvează profil",
    myDrafts: "Proiectele Mele",
    newDraft: "Proiect Nou",
    publishToStore: "Publică pe Store",
    storeTitle: "Librăria Publică",
    storeIntro: "Explorează cărți scrise și publicate de alți cititori din comunitate. Descarcă-le gratuit direct pe raftul tău!",
    downloadBook: "Descarcă carte",
    likes: "Aprecieri",
    downloads: "Descărcări",
    quickStats: "Statistici Rapide",
    instructionsTitle: "Cum Funcționează Rețelele de Paginare?",
    instructionsText1: "1. Întoarcerea fizică a paginii: Faceți clic oriunde pe marginea dreaptă a cărții sau folosiți glisarea (swipe) pentru a deschide foaia următoare în stil 3D realist.",
    instructionsText2: "2. Căutare rapidă termeni: Apăsați pe tab-ul de căutare pentru a localiza instant orice pasaj într-un singur loc din toți indexii.",
    instructionsText3: "3. Atelierul autorului: Scrieți propria poveste, împărțiți-o pe capitole și publicați-o direct pe Librăria Store.",
  },
  en: {
    library: "Library",
    authorAtelier: "Author Atelier",
    store: "Store Shelf",
    importBook: "Import Book",
    howItWorks: "How it works",
    welcomeTitle: "Your literary universe beautifully crafted in",
    welcomeTitleAccent: "3D pages",
    welcomeSubtitle: "Welcome to the interactive reader dedicated to book lovers. Import EPUB or clean TXT formats, pick your favorite vintage parchment theme and enjoy the responsive paginating bend motions as you swipe.",
    importFirst: "IMPORT FIRST EBOOK",
    supportNote: "Optimized for tablets of any size and mobile devices.",
    ownBooks: "My Books",
    readingProgress: "In Progress",
    totalChapters: "Total Chapters",
    activeBookmarks: "Active Bookmarks",
    continueReading: "Continue Reading",
    deleteBookConfirm: "Are you sure you want to delete this book from your collection?",
    deleteBookmarkConfirm: "Are you sure you want to delete this bookmark?",
    chapters: "Contents",
    bookmarks: "Bookmarks",
    search: "Search",
    searchPlaceholder: "Search inside this book...",
    fontSize: "Font size",
    lineHeight: "Line height",
    layoutType: "Layout style",
    twoPageSpread: "Double-page",
    singlePage: "Single-page",
    noBooks: "No books in your library shelf yet.",
    dragDrop: "Drag and drop ebook files here, or click to browse",
    back: "Back",
    soundEffects: "Sound effects",
    closeReader: "Close",
    translateBook: "Translate",
    translateBookTitle: "AI Smart Translator",
    translateChapterBtn: "Translate to",
    translatingText: "Translating content via AI...",
    translationSuccess: "Chapter translated successfully!",
    translationError: "Translation failed. Please try again.",
    originalLanguage: "Original text (Book language)",
    viewOriginalText: "Show original text",
    translatedByAI: "Translated automatically with Gemini AI",
    aboutBook: "About Book",
    authorName: "Author",
    description: "Description",
    emptyBookmarks: "No bookmarks placed on the book pages.",
    addBookmarkTip: "Click the bookmark flag in the corner of the page while reading to save important sections.",
    bookmarksCount: "BOOKMARKS",
    chaptersCount: "CHAPTERS",
    searchResultsCount: "SEARCH RESULTS IN BOOK",
    searchNoResults: "No fragments found in the text.",
    searchAtLeast2: "Enter at least 2 characters to search...",
    secuEmptySearch: "Locate phrases or words",
    searchSecuTip: "Write a word or phrase in the box above to locate references and highlight them inside the book pages.",
    searchTitleHint: "search keywords",
    themeParchment: "Parchment",
    themeWarmPaper: "Warm Paper",
    themeSlateDark: "Slate Dark",
    themeMidnightVelvet: "Midnight Velvet",
    themeClassicWhite: "Classic White",
    aboutAuthor: "About Author Atelier",
    authorIntro: "Write and publish your own literature works. You can become the author of books sitting on the shelf!",
    createProfile: "Create Author Profile",
    penName: "Pen Name",
    email: "Author Email",
    saveProfile: "Save Profile",
    myDrafts: "My Drafts",
    newDraft: "New Draft",
    publishToStore: "Publish to Store",
    storeTitle: "Community Store",
    storeIntro: "Explore books written and published by other readers in the community. Download them for free onto your bookshelf!",
    downloadBook: "Download Book",
    likes: "Likes",
    downloads: "Downloads",
    quickStats: "Quick Stats",
    instructionsTitle: "How Paginating Works?",
    instructionsText1: "1. Physical sheet bending: Click anywhere on the right-hand page border or drag/swipe on touch-input devices to bend the page forward in a realistic 3D aesthetic.",
    instructionsText2: "2. Instant indexing search: Search keywords in the corresponding tab inside the sidebar to highlight them immediately.",
    instructionsText3: "3. Publish to community: Create original transcripts, organize chapters, and release them as custom releases to the public database Store.",
  },
  es: {
    library: "Biblioteca",
    authorAtelier: "Taller del Autor",
    store: "Librería Store",
    importBook: "Importar Libro",
    howItWorks: "Cómo funciona",
    welcomeTitle: "Tu universo literario plasmado en",
    welcomeTitleAccent: "páginas 3D",
    welcomeSubtitle: "Bienvenido al lector interactivo para los amantes de los libros. Importe EPUB o TXT, escoja su tema vintage de pergamino y disfrute de los movimientos realistas de flexión de página al deslizar.",
    importFirst: "IMPORTAR PRIMER EBOOK",
    supportNote: "Soporta tabletas de cualquier tamaño y teléfonos móviles.",
    ownBooks: "Tus Volúmenes",
    readingProgress: "En Progreso",
    totalChapters: "Capítulos Totales",
    activeBookmarks: "Marcadores Activos",
    continueReading: "Continuar Leyendo",
    deleteBookConfirm: "¿Seguro que desea eliminar este libro de su colección?",
    deleteBookmarkConfirm: "¿Seguro que desea eliminar este marcador?",
    chapters: "Índice",
    bookmarks: "Marcadores",
    search: "Buscar",
    searchPlaceholder: "Buscar en este libro...",
    fontSize: "Tamaño de letra",
    lineHeight: "Espaciado",
    layoutType: "Modo de Vista",
    twoPageSpread: "Páginas dobles",
    singlePage: "Página única",
    noBooks: "No hay libros en tu biblioteca.",
    dragDrop: "Arrastre los archivos aquí o haga clic para cargarlos",
    back: "Atrás",
    soundEffects: "Efectos de sonido",
    closeReader: "Cerrar",
    translateBook: "Traducir",
    translateBookTitle: "Traductor Inteligente de IA",
    translateChapterBtn: "Traducir al",
    translatingText: "Traduciendo contenido mediante IA...",
    translationSuccess: "¡Capítulo traducido con éxito!",
    translationError: "Error al traducir. Inténtelo de nuevo.",
    originalLanguage: "Texto original (Idioma del libro)",
    viewOriginalText: "Ver texto original",
    translatedByAI: "Traducido automáticamente con Gemini AI",
    aboutBook: "Acerca del Libro",
    authorName: "Autor",
    description: "Descripción",
    emptyBookmarks: "No se han colocado marcadores en el libro.",
    addBookmarkTip: "Haga clic en la cinta de marcadores en la esquina superior mientras lee para guardar párrafos importantes.",
    bookmarksCount: "MARCADORES",
    chaptersCount: "CAPÍTULOS",
    searchResultsCount: "RESULTADOS DE BÚSQUEDA",
    searchNoResults: "No se han encontrado pasajes.",
    searchAtLeast2: "Escriba un mínimo de 2 caracteres...",
    secuEmptySearch: "Localizar frases o palabras",
    searchSecuTip: "Escriba una frase en la casilla superior para encontrar coincidencias y resaltarlas en las hojas del libro.",
    searchTitleHint: "buscar palabras clave",
    themeParchment: "Pergamino",
    themeWarmPaper: "Papel Caliente",
    themeSlateDark: "Pizarra Oscura",
    themeMidnightVelvet: "Terciopelo Nocturno",
    themeClassicWhite: "Blanco Clásico",
    aboutAuthor: "Taller del Autor",
    authorIntro: "Escriba y publique sus propias creaciones literarias. ¡Conviértase en el autor de las obras que descansan en el estante!",
    createProfile: "Crear perfil de autor",
    penName: "Pseudónimo",
    email: "Email del autor",
    saveProfile: "Guardar Perfil",
    myDrafts: "Mis Proyectos",
    newDraft: "Nuevo Proyecto",
    publishToStore: "Publicar en Store",
    storeTitle: "Librería Comunitaria",
    storeIntro: "Explore libros creados y compartidos por la comunidad de lectores. ¡Descárguelos gratis a su estantería!",
    downloadBook: "Descargar",
    likes: "Me Gusta",
    downloads: "Descargas",
    quickStats: "Estadísticas",
    instructionsTitle: "¿Cómo funciona el doblado?",
    instructionsText1: "1. Doblamiento de página: Haga clic en los bordes de la derecha o arrastre en dispositivos táctiles para doblar la página dinámicamente con estética 3D.",
    instructionsText2: "2. Indexador de búsqueda: Localice términos y resáltelos al instante en las páginas del libro.",
    instructionsText3: "3. Redactar historias: Redacte novelas, organice capítulos y regístrelas gratis en la librería comunitaria pública.",
  },
  fr: {
    library: "Bibliothèque",
    authorAtelier: "Atelier d'Auteur",
    store: "Librairie Store",
    importBook: "Importer",
    howItWorks: "Comment ça marche",
    welcomeTitle: "Votre univers littéraire transposé en",
    welcomeTitleAccent: "pages 3D",
    welcomeSubtitle: "Bienvenue sur le lecteur interactif dédié aux amoureux du livre. Importez des fichiers EPUB ou TXT, choisissez votre thème de parchemin vintage et profitez des animations fluides de pliage de page lors du balayage de l'écran.",
    importFirst: "IMPORTER LE PREMIER LIVRE",
    supportNote: "Prend en charge les tablettes et smartphones de toutes tailles.",
    ownBooks: "Mes Livres",
    readingProgress: "En cours",
    totalChapters: "Chapitres Totaux",
    activeBookmarks: "Signets Actifs",
    continueReading: "Continuer la lecture",
    deleteBookConfirm: "Êtes-vous sûr de vouloir supprimer ce livre de votre étagère ?",
    deleteBookmarkConfirm: "Êtes-vous sûr de vouloir supprimer ce signet ?",
    chapters: "Sommaire",
    bookmarks: "Signets",
    search: "Rechercher",
    searchPlaceholder: "Chercher dans ce livre...",
    fontSize: "Taille de police",
    lineHeight: "Hauteur de ligne",
    layoutType: "Type d'affichage",
    twoPageSpread: "Double page",
    singlePage: "Simple page",
    noBooks: "Aucun livre dans votre bibliothèque.",
    dragDrop: "Glissez-déposez des fichiers ici ou cliquez pour parcourir",
    back: "Retour",
    soundEffects: "Effets sonores",
    closeReader: "Fermer",
    translateBook: "Traduire",
    translateBookTitle: "Traducteur Intelligent IA",
    translateChapterBtn: "Traduire en",
    translatingText: "Traduction du texte par IA...",
    translationSuccess: "Chapitre traduit avec succès !",
    translationError: "Erreur de traduction. Veuillez réessayer.",
    originalLanguage: "Texte original (Langue du livre)",
    viewOriginalText: "Afficher le texte original",
    translatedByAI: "Traduit automatiquement avec Gemini AI",
    aboutBook: "À propos du livre",
    authorName: "Auteur",
    description: "Description",
    emptyBookmarks: "Aucun signet ajouté sur les pages.",
    addBookmarkTip: "Cliquez sur l'onglet signet dans le coin de la page pendant votre lecture pour enregistrer des passages clés.",
    bookmarksCount: "SIGNETS",
    chaptersCount: "CHAPITRES",
    searchResultsCount: "NOTICES DE RECHERCHE",
    searchNoResults: "Aucun passage correspondant trouvé.",
    searchAtLeast2: "Saisissez au moins 2 caractères...",
    secuEmptySearch: "Localiser des phrases",
    searchSecuTip: "Tapez un mot ou une phrase ci-dessus pour situer et surligner dynamiquement les occurrences.",
    searchTitleHint: "mots-clés de recherche",
    themeParchment: "Parchemin",
    themeWarmPaper: "Papier Chaud",
    themeSlateDark: "Ardoise Sombre",
    themeMidnightVelvet: "Velours de Nuit",
    themeClassicWhite: "Blanc Classique",
    aboutAuthor: "Atelier des Auteurs",
    authorIntro: "Rédigez et publiez vos propres créations. Devenez l'auteur des romans imprimés sur nos étagères !",
    createProfile: "Créer un profil d'auteur",
    penName: "Pseudonyme",
    email: "E-mail de l'auteur",
    saveProfile: "Sauvegarder",
    myDrafts: "Mes Brouillons",
    newDraft: "Nouveau Projet",
    publishToStore: "Publier",
    storeTitle: "Librairie de la Communauté",
    storeIntro: "Découvrez des livres créés et partagés par d'autres lecteurs de la communauté. Téléchargez-les gratuitement !",
    downloadBook: "Télécharger",
    likes: "J'aime",
    downloads: "Téléchargements",
    quickStats: "Statistiques",
    instructionsTitle: "Comment fonctionne le pliage ?",
    instructionsText1: "1. Flexion de feuille réaliste : Cliquez sur les lisières droites ou balayez sur écran tactile pour courber la feuille en effet 3D exceptionnel.",
    instructionsText2: "2. Saisie de recherche : Retrouvez rapidement n'importe quelle citation et surlignez-la instantanément.",
    instructionsText3: "3. Éditeur de texte complet : Créez des récits originaux, divisez-les en chapitres et exportez-les gratuitement sur le Store.",
  },
  it: {
    library: "Libreria",
    authorAtelier: "Atelier Autore",
    store: "Libreria Store",
    importBook: "Importa Libro",
    howItWorks: "Come funziona",
    welcomeTitle: "Il tuo universo letterario tradotto in",
    welcomeTitleAccent: "pagine 3D",
    welcomeSubtitle: "Benvenuto nel lettore interattivo per la lettura di libri digitali. Importa Epub o TXT, scegli il tuo tema pergamena vintage classico e sperimenta i passaggi di pagina reali ed evocativi.",
    importFirst: "IMPORTA IL PRIMO EBOOK",
    supportNote: "Ottimizzato per tablet e telefoni cellulari di qualsiasi dimensione.",
    ownBooks: "Miei Volumi",
    readingProgress: "In Corso",
    totalChapters: "Capitoli Totali",
    activeBookmarks: "Segnalibri Attivi",
    continueReading: "Continua Lettura",
    deleteBookConfirm: "Sei sicuro di voler eliminare questo libro dalla tua collezione?",
    deleteBookmarkConfirm: "Sei sicuro di voler rimuovere questo segnalibro?",
    chapters: "Indice",
    bookmarks: "Segnalibri",
    search: "Cerca",
    searchPlaceholder: "Cerca all'interno del libro...",
    fontSize: "Grandezza testo",
    lineHeight: "Altezza riga",
    layoutType: "Visualizzazione",
    twoPageSpread: "Doppia pagina",
    singlePage: "Pagina singola",
    noBooks: "La tua biblioteca è vuota.",
    dragDrop: "Trascina i file epub o txt qui o fai clic per caricarli",
    back: "Indietro",
    soundEffects: "Effetti sonori",
    closeReader: "Chiudi",
    translateBook: "Traduci",
    translateBookTitle: "Traduttore Intelligente IA",
    translateChapterBtn: "Traduci in",
    translatingText: "Traduzione del testo in corso tramite IA...",
    translationSuccess: "Capitolo tradotto con successo!",
    translationError: "Errore di traduzione. Riprova.",
    originalLanguage: "Testo original (Lingua del libro)",
    viewOriginalText: "Mostra testo originale",
    translatedByAI: "Tradotto automaticamente con Gemini AI",
    aboutBook: "Dettagli del Libro",
    authorName: "Autore",
    description: "Descrizione",
    emptyBookmarks: "Nessun segnalibro aggiunto su questo libro.",
    addBookmarkTip: "Clicca la fascetta del segnalibro sull'angolo in alto mentre leggi per salvare i passaggi preferiti.",
    bookmarksCount: "SEGNALIBRI",
    chaptersCount: "CAPITOLI",
    searchResultsCount: "RISULTATI DELLA RICERCA",
    searchNoResults: "Nessuna corrispondenza trovata.",
    searchAtLeast2: "Digita almeno 2 caratteri...",
    secuEmptySearch: "Trova espressioni o parole",
    searchSecuTip: "Inserisci un termine di ricerca per visualizzare ed evidenziare tutti i riferimenti significativi.",
    searchTitleHint: "parole chiave",
    themeParchment: "Pergamena",
    themeWarmPaper: "Carta Calda",
    themeSlateDark: "Ardesia Scuro",
    themeMidnightVelvet: "Velluto Notturno",
    themeClassicWhite: "Bianco Classico",
    aboutAuthor: "Laboratorio Scrittura",
    authorIntro: "Crea e pubblica le tue opere letterarie. Diventa l'autore dei sogni visibili in biblioteca!",
    createProfile: "Crea profilo autore",
    penName: "Pseudonimo",
    email: "Email autore",
    saveProfile: "Salva Profilo",
    myDrafts: "I Miei Progetti",
    newDraft: "Nuovo Progetto",
    publishToStore: "Pubblica",
    storeTitle: "Negozio Comunitario",
    storeIntro: "Explore books written and published by other readers in the community. Download them for free onto your bookshelf!",
    downloadBook: "Scarica",
    likes: "Mi Piace",
    downloads: "Download",
    quickStats: "Statistiche",
    instructionsTitle: "Come funziona la paginazione interattiva?",
    instructionsText1: "1. Piegatura del foglio: Clicca sul margine destro o trascina per sfogliare realisticamente i fogli in 3D.",
    instructionsText2: "2. Ricerca termini: Cerca qualsiasi termine all'interno della barra laterale per evidenziarlo all'istante.",
    instructionsText3: "3. Atelier scrittore: Componi le tue opere personali suddivise in capitoli e caricale nel negozio online.",
  },
};

// Simple global listener-based store for language updates so all components automatically re-render when language changes
let currentLang: LanguageCode = (localStorage.getItem("ebook-reader-lang") as LanguageCode) || "ro";
const listeners = new Set<() => void>();

export function getAppLanguage(): LanguageCode {
  return currentLang;
}

export function setAppLanguage(lang: LanguageCode) {
  currentLang = lang;
  localStorage.setItem("ebook-reader-lang", lang);
  listeners.forEach((l) => l());
}

export function useTranslation() {
  const [lang, setLang] = useState<LanguageCode>(currentLang);

  useEffect(() => {
    const handleUpdate = () => {
      setLang(currentLang);
    };
    listeners.add(handleUpdate);
    return () => {
      listeners.delete(handleUpdate);
    };
  }, []);

  const t = (key: keyof typeof UI_TRANSLATIONS["ro"]) => {
    return UI_TRANSLATIONS[lang]?.[key] || UI_TRANSLATIONS["ro"][key];
  };

  return { t, currentLanguage: lang, setLanguage: setAppLanguage, languages: LANGUAGES };
}
